// Single source of truth for component -> category mapping.
// Used by all three Storybooks (React, Svelte, Web Components) to keep the
// sidebar identical across renderers. Max 12 categories.

export const CATEGORY_ORDER = [
  'Foundations',
  'Layout',
  'Inputs',
  'Selection & menus',
  'Navigation',
  'Feedback',
  'Data display',
  'Charts: comparison',
  'Charts: time-series',
  'Charts: distribution',
  'Charts: hierarchy & flow',
  'Specialised',
] as const

export type Category = (typeof CATEGORY_ORDER)[number]

export const COMPONENT_CATEGORY: Record<string, Category> = {
  // Layout
  AppShell: 'Layout',
  AppLayout: 'Layout',
  Card: 'Layout',
  PageHeader: 'Layout',
  ResizablePanel: 'Layout',
  Drawer: 'Layout',
  Modal: 'Layout',
  Carousel: 'Layout',

  // Inputs
  Button: 'Inputs',
  IconButton: 'Inputs',
  Input: 'Inputs',
  Textarea: 'Inputs',
  Select: 'Inputs',
  Combobox: 'Inputs',
  MultiSelect: 'Inputs',
  Checkbox: 'Inputs',
  RadioGroup: 'Inputs',
  Toggle: 'Inputs',
  Slider: 'Inputs',
  RangeSlider: 'Inputs',
  DatePicker: 'Inputs',
  DateRangePicker: 'Inputs',
  TimePicker: 'Inputs',
  NumberInput: 'Inputs',
  ColorPicker: 'Inputs',
  FileUpload: 'Inputs',
  OTPInput: 'Inputs',
  PasswordInput: 'Inputs',
  IPInput: 'Inputs',
  MACInput: 'Inputs',
  CIDRInput: 'Inputs',
  DurationInput: 'Inputs',
  Kbd: 'Inputs',
  InputGroup: 'Inputs',
  TagInput: 'Inputs',
  SegmentedControl: 'Inputs',
  ToggleGroup: 'Inputs',
  SplitButton: 'Inputs',
  StarRating: 'Inputs',

  // Selection & menus
  ActionMenu: 'Selection & menus',
  ContextMenu: 'Selection & menus',
  CommandPalette: 'Selection & menus',
  Menubar: 'Selection & menus',
  Popover: 'Selection & menus',
  HoverCard: 'Selection & menus',
  Tooltip: 'Selection & menus',
  ContextualHelp: 'Selection & menus',
  ColumnToggle: 'Selection & menus',
  FilterBuilder: 'Selection & menus',

  // Navigation
  Breadcrumb: 'Navigation',
  Pagination: 'Navigation',
  Stepper: 'Navigation',
  Tabs: 'Navigation',
  SkipLink: 'Navigation',
  TimeRange: 'Navigation',

  // Feedback
  Alert: 'Feedback',
  Banner: 'Feedback',
  Callout: 'Feedback',
  Toast: 'Feedback',
  ConfirmDialog: 'Feedback',
  Spinner: 'Feedback',
  Skeleton: 'Feedback',
  EmptyState: 'Feedback',
  ProgressBar: 'Feedback',
  StackedProgress: 'Feedback',
  Signal: 'Feedback',
  StatusIndicator: 'Feedback',
  HealthBar: 'Feedback',
  Gauge: 'Feedback',
  CountUp: 'Feedback',
  Stat: 'Feedback',
  NotificationPanel: 'Feedback',
  ActivityFeed: 'Feedback',
  InlineEdit: 'Feedback',
  CopyButton: 'Feedback',

  // Data display
  Avatar: 'Data display',
  AvatarGroup: 'Data display',
  Badge: 'Data display',
  Pill: 'Data display',
  Tag: 'Data display',
  Accordion: 'Data display',
  ExpandableRow: 'Data display',
  SortableTable: 'Data display',
  Timeline: 'Data display',
  TreeView: 'Data display',
  TreeBrowser: 'Data display',
  KVTable: 'Data display',
  JsonViewer: 'Data display',
  CodeBlock: 'Data display',
  LogViewer: 'Data display',
  GroupedList: 'Data display',
  RankedList: 'Data display',
  SortableList: 'Data display',
  Spoiler: 'Data display',
  VirtualList: 'Data display',
  KanbanBoard: 'Data display',
  SelectionToolbar: 'Data display',
  TransferList: 'Data display',
  SwitchPortGrid: 'Data display',

  // Charts: comparison
  BarChart: 'Charts: comparison',
  StackedBarChart: 'Charts: comparison',
  MirroredBarChart: 'Charts: comparison',
  LollipopChart: 'Charts: comparison',
  DotPlot: 'Charts: comparison',
  BulletChart: 'Charts: comparison',
  BumpChart: 'Charts: comparison',
  SlopeChart: 'Charts: comparison',
  DumbbellChart: 'Charts: comparison',
  ParetoChart: 'Charts: comparison',
  MarimekkoChart: 'Charts: comparison',
  WaffleChart: 'Charts: comparison',
  RadialBarChart: 'Charts: comparison',
  NightingaleChart: 'Charts: comparison',
  RadarChart: 'Charts: comparison',

  // Charts: time-series
  LineChart: 'Charts: time-series',
  AreaChart: 'Charts: time-series',
  StepChart: 'Charts: time-series',
  ErrorBandChart: 'Charts: time-series',
  AnnotatedTimeSeries: 'Charts: time-series',
  ThresholdAreaChart: 'Charts: time-series',
  StreamGraph: 'Charts: time-series',
  HorizonChart: 'Charts: time-series',
  CandlestickChart: 'Charts: time-series',
  GanttChart: 'Charts: time-series',
  UptimeTimeline: 'Charts: time-series',
  DualAxisChart: 'Charts: time-series',
  Sparkline: 'Charts: time-series',
  SparklineMatrix: 'Charts: time-series',

  // Charts: distribution
  Histogram: 'Charts: distribution',
  BoxPlot: 'Charts: distribution',
  ViolinPlot: 'Charts: distribution',
  RidgelinePlot: 'Charts: distribution',
  BeeswarmChart: 'Charts: distribution',
  BubbleChart: 'Charts: distribution',
  ScatterPlot: 'Charts: distribution',
  QuadrantChart: 'Charts: distribution',
  HexbinChart: 'Charts: distribution',
  ContourPlot: 'Charts: distribution',
  CumulativeDistribution: 'Charts: distribution',
  ParallelCoordinates: 'Charts: distribution',
  CorrelationMatrix: 'Charts: distribution',
  MatrixChart: 'Charts: distribution',
  HeatMap: 'Charts: distribution',
  PolarHeatmap: 'Charts: distribution',
  CalendarHeatmap: 'Charts: distribution',
  PunchCard: 'Charts: distribution',
  StripeChart: 'Charts: distribution',
  WordCloud: 'Charts: distribution',

  // Charts: hierarchy & flow
  TreeMap: 'Charts: hierarchy & flow',
  SunburstChart: 'Charts: hierarchy & flow',
  IcicleChart: 'Charts: hierarchy & flow',
  CirclePacking: 'Charts: hierarchy & flow',
  Dendrogram: 'Charts: hierarchy & flow',
  ChordDiagram: 'Charts: hierarchy & flow',
  SankeyDiagram: 'Charts: hierarchy & flow',
  FunnelChart: 'Charts: hierarchy & flow',
  WaterfallChart: 'Charts: hierarchy & flow',
  ArcDiagram: 'Charts: hierarchy & flow',
  ForceGraph: 'Charts: hierarchy & flow',
  VennDiagram: 'Charts: hierarchy & flow',
  FlameGraph: 'Charts: hierarchy & flow',
  PieChart: 'Charts: hierarchy & flow',
  Donut: 'Charts: hierarchy & flow',
}

export function categoryFor(componentName: string): Category {
  return COMPONENT_CATEGORY[componentName] ?? 'Specialised'
}

export function storyTitle(componentName: string): string {
  return `${categoryFor(componentName)}/${componentName}`
}
