// AUTO-GENERATED by scripts/generate-stories-react.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/react'
import { FIXTURES } from '../../../../packages/react/test-fixtures/fixtures.js'

const variants = FIXTURES.CorrelationMatrix!

const meta: Meta = {
  title: 'Charts: distribution/CorrelationMatrix',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: variants[0]!.name,
  render: () => variants[0]!.node,
}
