// AUTO-GENERATED by scripts/generate-stories-react.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/react'
import { FIXTURES } from '../../../../packages/react/test-fixtures/fixtures.js'

const variants = FIXTURES.HoverCard!

const meta: Meta = {
  title: 'Selection & menus/HoverCard',
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component:
          'Rich, **non-essential** content about its trigger: a bold `heading`, a `description`, and optional rich `content` (preview, key/value rows). Opens **instantly** on hover and keyboard focus; hoverable, and dismissible with `Escape`. Everything in it must also be reachable elsewhere. A control’s name belongs in a Tooltip; interactive content in a Popover.',
      },
    },
  },
  tags: ['autodocs'],
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: variants[0]!.name,
  render: () => variants[0]!.node,
}

export const Variant1: Story = {
  name: variants[1]!.name,
  render: () => variants[1]!.node,
}

export const Variant2: Story = {
  name: variants[2]!.name,
  render: () => variants[2]!.node,
}
