// AUTO-GENERATED by scripts/generate-stories-react.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/react'
import { FIXTURES } from '../../../../packages/react/test-fixtures/fixtures.js'

const variants = FIXTURES.Pill!

const meta: Meta = {
  title: 'Data display/Pill',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: variants[0]!.name,
  render: () => variants[0]!.node,
}

export const Variant1: Story = {
  name: variants[1]!.name,
  render: () => variants[1]!.node,
}

export const Variant2: Story = {
  name: variants[2]!.name,
  render: () => variants[2]!.node,
}

export const Variant3: Story = {
  name: variants[3]!.name,
  render: () => variants[3]!.node,
}

export const Variant4: Story = {
  name: variants[4]!.name,
  render: () => variants[4]!.node,
}

export const Variant5: Story = {
  name: variants[5]!.name,
  render: () => variants[5]!.node,
}
