// AUTO-GENERATED by scripts/generate-stories-react.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/react'
import { FIXTURES } from '../../../../packages/react/test-fixtures/fixtures.js'

const variants = FIXTURES.Popover!

const meta: Meta = {
  title: 'Selection & menus/Popover',
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component:
          'A **click-opened**, interactive surface anchored to its trigger: menus, pickers, filters. Focus moves into the panel and returns to the trigger; closes on outside click and `Escape`. For a control’s name use a Tooltip; for read-only extra detail on hover use a HoverCard.',
      },
    },
  },
  tags: ['autodocs'],
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: variants[0]!.name,
  render: () => variants[0]!.node,
}

export const Variant1: Story = {
  name: variants[1]!.name,
  render: () => variants[1]!.node,
}
