// AUTO-GENERATED by scripts/generate-stories-react.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/react';
import { FIXTURES } from '../../../../packages/react/test-fixtures/fixtures.js';

const variants = FIXTURES.Spinner!;

const meta: Meta = {
  title: 'Feedback/Spinner',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: variants[0]!.name,
  render: () => variants[0]!.node as any,
};

export const Variant1: Story = {
  name: variants[1]!.name,
  render: () => variants[1]!.node as any,
};

export const Variant2: Story = {
  name: variants[2]!.name,
  render: () => variants[2]!.node as any,
};
