// AUTO-GENERATED by scripts/generate-stories-react.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/react'
import { FIXTURES } from '../../../../packages/react/test-fixtures/fixtures.js'

const variants = FIXTURES.Tooltip!

const meta: Meta = {
  title: 'Selection & menus/Tooltip',
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component:
          'The **name** of a control: short, plain, non-interactive text. Opens after **1 s** of hover, **instantly** on keyboard focus, and on a touch long-press; closes on pointer leave, blur, `Escape` or pressing the control. Never the only carrier of meaning: an icon-only control inside is named after the tooltip, a control with its own name keeps it. Replaces the native `title` attribute. Rich content belongs in a HoverCard; interactive content in a Popover.',
      },
    },
  },
  tags: ['autodocs'],
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: variants[0]!.name,
  render: () => variants[0]!.node,
}

export const Variant1: Story = {
  name: variants[1]!.name,
  render: () => variants[1]!.node,
}
