blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/webbertakken/dash-ui/discussions
    about: Use Discussions for questions, design conversations and showcase.
