#!/usr/bin/env tsx
// Vendors the self-hosted fonts into @w5-ui/tokens.
//
// Source: the pinned Fontsource variable-font packages below (SIL OFL 1.1).
// Output:  packages/tokens/src/fonts/*.woff2 + <Font>-OFL.txt
//          packages/tokens/src/fonts.css (@font-face, one per script subset)
//
// Re-run after bumping a version: `yarn tsx scripts/fonts/vendor-fonts.ts`.
// Only the upright variable `wght` axis is vendored; subsets load on demand
// through `unicode-range`, so a Latin page fetches just the Latin files.

import { execFileSync } from 'node:child_process'
import {
  copyFileSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const TOKENS = path.join(REPO, 'packages/tokens/src')
const FONTS = path.join(TOKENS, 'fonts')

const SOURCES = [
  {
    pkg: '@fontsource-variable/inter',
    version: '5.3.0',
    family: 'Inter',
    licence: 'Inter-OFL.txt',
  },
  {
    pkg: '@fontsource-variable/jetbrains-mono',
    version: '5.3.0',
    family: 'JetBrains Mono',
    licence: 'JetBrainsMono-OFL.txt',
  },
] as const

interface Face {
  subset: string
  weight: string
  file: string
  unicodeRange: string
}

function parseFaces(css: string): Face[] {
  return Array.from(
    css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g),
    ([, subset, body]) => {
      const prop = (name: string) => {
        const value = body!.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1]?.trim()
        if (!value) throw new Error(`${subset}: missing ${name}`)
        return value
      }
      return {
        subset: subset!,
        weight: prop('font-weight'),
        file: path.basename(prop('src').match(/url\(([^)]+)\)/)![1]!),
        unicodeRange: prop('unicode-range'),
      }
    },
  )
}

function unpack(pkg: string, version: string, into: string): string {
  const tarball = execFileSync('npm', ['pack', '--silent', `${pkg}@${version}`], { cwd: into })
    .toString()
    .trim()
  const dir = path.join(into, pkg.replace(/\W+/g, '-'))
  mkdirSync(dir)
  execFileSync('tar', ['-xzf', path.join(into, tarball), '-C', dir])
  return path.join(dir, 'package')
}

const work = mkdtempSync(path.join(tmpdir(), 'w5-fonts-'))
rmSync(FONTS, { recursive: true, force: true })
mkdirSync(FONTS, { recursive: true })

const blocks: string[] = []
try {
  for (const source of SOURCES) {
    const root = unpack(source.pkg, source.version, work)
    const faces = parseFaces(readFileSync(path.join(root, 'wght.css'), 'utf8'))
    if (!faces.some((f) => f.subset.endsWith('-latin-wght-normal'))) {
      throw new Error(`${source.pkg}: no latin subset in wght.css`)
    }
    copyFileSync(path.join(root, 'LICENSE'), path.join(FONTS, source.licence))
    for (const face of faces) {
      copyFileSync(path.join(root, 'files', face.file), path.join(FONTS, face.file))
      blocks.push(`/* ${face.subset} */
@font-face {
  font-family: '${source.family}';
  font-style: normal;
  font-display: swap;
  font-weight: ${face.weight};
  src: url('./fonts/${face.file}') format('woff2');
  unicode-range: ${face.unicodeRange};
}`)
    }
    console.log(`${source.pkg}@${source.version}: ${faces.length} subsets`)
  }
} finally {
  rmSync(work, { recursive: true, force: true })
}

const header = `/* AUTO-GENERATED by scripts/fonts/vendor-fonts.ts. Do not edit by hand.
   Self-hosted variable fonts (SIL OFL 1.1, licences in ./fonts/). Each script
   subset downloads only when the page uses characters in its unicode-range. */
`
const fontsCss = path.join(TOKENS, 'fonts.css')
writeFileSync(fontsCss, `${header}\n${blocks.join('\n\n')}\n`)
// Keep the generated file byte-identical to what `yarn format` produces.
execFileSync('yarn', ['oxfmt', '--write', fontsCss], { cwd: REPO })
console.log(`Wrote ${readdirSync(FONTS).length} files to ${path.relative(REPO, FONTS)}`)
