// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Feedback/ActivityFeed',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { items: [{ id: '1', title: 'Joined', time: 'now' }] }
    const el = document.createElement('uni-activity-feed') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'busy',
  render: () => {
    const props: Record<string, unknown> = {
      items: [{ id: '1', title: 'x', description: 'd', time: 'now', severity: 'warn' }],
      busy: true,
      autoScroll: true,
    }
    const el = document.createElement('uni-activity-feed') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'empty',
  render: () => {
    const props: Record<string, unknown> = { items: [] }
    const el = document.createElement('uni-activity-feed') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
