// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Selection & menus/ActionMenu',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      items: [
        { id: 'a', label: 'A' },
        { id: 'b', label: 'B', danger: true, disabled: true },
      ],
      onAction: () => {},
    }
    const el = document.createElement('uni-action-menu')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
