// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Feedback/Alert',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'info',
  render: () => {
    const props: Record<string, unknown> = {}
    const el = document.createElement('uni-alert') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v
    el.textContent = 'info'
    return el
  },
}

export const Variant1: Story = {
  name: 'success',
  render: () => {
    const props: Record<string, unknown> = { variant: 'success', onDismiss: () => {} }
    const el = document.createElement('uni-alert') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v
    el.textContent = 'ok'
    return el
  },
}

export const Variant2: Story = {
  name: 'warn',
  render: () => {
    const props: Record<string, unknown> = { variant: 'warn' }
    const el = document.createElement('uni-alert') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v
    el.textContent = 'w'
    return el
  },
}

export const Variant3: Story = {
  name: 'danger',
  render: () => {
    const props: Record<string, unknown> = { variant: 'danger' }
    const el = document.createElement('uni-alert') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v
    el.textContent = 'd'
    return el
  },
}
