// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: time-series/AnnotatedTimeSeries',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "data": [1, 4, 2, 7, 5, 9], "labels": ["M", "T", "W", "T", "F", "S"], "annotations": [{ "index": 2, "label": "s" }] };
    const el = document.createElement('uni-annotated-time-series');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "no annotations",
  render: () => {
    const props: Record<string, unknown> = { "data": [1, 4, 2, 7, 5, 9] };
    const el = document.createElement('uni-annotated-time-series');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
