// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Data display/Avatar',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "initials",
  render: () => {
    const props: Record<string, unknown> = { "initials": "WB" };
    const el = document.createElement('uni-avatar');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "image",
  render: () => {
    const props: Record<string, unknown> = { "src": "data:image/svg+xml,<svg/>", "alt": "me", "size": "lg", "status": "online" };
    const el = document.createElement('uni-avatar');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant2: Story = {
  name: "away",
  render: () => {
    const props: Record<string, unknown> = { "status": "away" };
    const el = document.createElement('uni-avatar');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant3: Story = {
  name: "sm",
  render: () => {
    const props: Record<string, unknown> = { "size": "sm" };
    const el = document.createElement('uni-avatar');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
