// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/AvatarGroup',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { avatars: [{ initials: 'A' }, { initials: 'B' }] }
    const el = document.createElement('uni-avatar-group') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'overflow',
  render: () => {
    const props: Record<string, unknown> = {
      avatars: [{ initials: 'A' }, { initials: 'B' }, { initials: 'C' }, { initials: 'D' }],
      max: 2,
      size: 'sm',
    }
    const el = document.createElement('uni-avatar-group') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
