// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: distribution/BoxPlot',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      series: [
        { label: 'A', q0: 1, q1: 3, q2: 5, q3: 7, q4: 9 },
        { label: 'B', q0: 0, q1: 2, q2: 4, q3: 6, q4: 8, color: '#0f0' },
      ],
    }
    const el = document.createElement('uni-box-plot') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'yRange',
  render: () => {
    const props: Record<string, unknown> = {
      series: [{ label: 'A', q0: 0, q1: 2, q2: 4, q3: 6, q4: 8 }],
      yRange: [0, 10],
    }
    const el = document.createElement('uni-box-plot') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
