// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: distribution/BubbleChart',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      points: [
        { x: 1, y: 2, r: 5 },
        { x: 4, y: 7, r: 10, color: '#0f0' },
      ],
    }
    const el = document.createElement('uni-bubble-chart')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'fixed',
  render: () => {
    const props: Record<string, unknown> = {
      points: [{ x: 1, y: 2, r: 5 }],
      xRange: [0, 10],
      yRange: [0, 10],
    }
    const el = document.createElement('uni-bubble-chart')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
