// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: comparison/BulletChart',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "items": [{ "label": "A", "value": 60, "target": 80, "ranges": [40, 70], "unit": "%" }, { "label": "B", "value": 100, "color": "#0f0" }] };
    const el = document.createElement('uni-bullet-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
