// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: comparison/BumpChart',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      labels: ['Mon', 'Tue', 'Wed', 'Thu'],
      series: [
        { label: 'A', ranks: [1, 2, 1, 3] },
        { label: 'B', ranks: [2, 1, 3, 1], color: '#0f0' },
      ],
    }
    const el = document.createElement('uni-bump-chart')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
