// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Inputs/Button',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "ghost",
  render: () => {
    const props: Record<string, unknown> = {  };
    const el = document.createElement('uni-button');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "Click";
    return el;
  },
};

export const Variant1: Story = {
  name: "primary",
  render: () => {
    const props: Record<string, unknown> = { "variant": "primary" };
    const el = document.createElement('uni-button');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "Save";
    return el;
  },
};

export const Variant2: Story = {
  name: "danger",
  render: () => {
    const props: Record<string, unknown> = { "variant": "danger" };
    const el = document.createElement('uni-button');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "Delete";
    return el;
  },
};

export const Variant3: Story = {
  name: "iconOnly",
  render: () => {
    const props: Record<string, unknown> = { "iconOnly": true, "title": "x" };
    const el = document.createElement('uni-button');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "x";
    return el;
  },
};

export const Variant4: Story = {
  name: "loading",
  render: () => {
    const props: Record<string, unknown> = { "loading": true };
    const el = document.createElement('uni-button');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "Loading";
    return el;
  },
};

export const Variant5: Story = {
  name: "disabled",
  render: () => {
    const props: Record<string, unknown> = { "disabled": true };
    const el = document.createElement('uni-button');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "d";
    return el;
  },
};
