// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: time-series/CandlestickChart',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "bars": [{ "open": 10, "close": 12, "high": 14, "low": 9 }, { "open": 12, "close": 11, "high": 13, "low": 10 }] };
    const el = document.createElement('uni-candlestick-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "yRange",
  render: () => {
    const props: Record<string, unknown> = { "bars": [{ "open": 1, "close": 2, "high": 3, "low": 0 }], "yRange": [0, 5], "unit": "$" };
    const el = document.createElement('uni-candlestick-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
