// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Layout/Card',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {}
    const el = document.createElement('uni-card') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v
    el.textContent = 'x'
    return el
  },
}

export const Variant1: Story = {
  name: 'span',
  render: () => {
    const props: Record<string, unknown> = { span: 2 }
    const el = document.createElement('uni-card') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v
    el.textContent = 'x'
    return el
  },
}
