// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Layout/Carousel',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'news',
      slides: [
        { id: '1', title: 'A', body: 'a' },
        { id: '2', title: 'B', body: 'b' },
      ],
    }
    const el = document.createElement('uni-carousel')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
