// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: hierarchy & flow/ChordDiagram',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      nodes: [{ label: 'A' }, { label: 'B', color: '#0f0' }, { label: 'C' }],
      matrix: [
        [0, 5, 2],
        [5, 0, 1],
        [2, 1, 0],
      ],
    }
    const el = document.createElement('uni-chord-diagram') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
