// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Inputs/CIDRInput',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { label: 'C' }
    const el = document.createElement('uni-cidrinput')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'controlled',
  render: () => {
    const props: Record<string, unknown> = { label: 'C', value: '10.0.0.0/8', onChange: () => {} }
    const el = document.createElement('uni-cidrinput')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'disabled',
  render: () => {
    const props: Record<string, unknown> = { label: 'C', disabled: true }
    const el = document.createElement('uni-cidrinput')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
