// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: hierarchy & flow/CirclePacking',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      items: [
        { id: 'a', label: 'A', value: 10 },
        { id: 'b', label: 'B', value: 20, color: '#0f0' },
      ],
    }
    const el = document.createElement('uni-circle-packing') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'many',
  render: () => {
    const props: Record<string, unknown> = {
      items: [
        { id: '0', label: 'n0', value: 100 },
        { id: '1', label: 'n1', value: 92 },
        { id: '2', label: 'n2', value: 84 },
        { id: '3', label: 'n3', value: 76 },
        { id: '4', label: 'n4', value: 68 },
        { id: '5', label: 'n5', value: 60 },
        { id: '6', label: 'n6', value: 52 },
        { id: '7', label: 'n7', value: 44 },
      ],
    }
    const el = document.createElement('uni-circle-packing') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'empty',
  render: () => {
    const props: Record<string, unknown> = { items: [] }
    const el = document.createElement('uni-circle-packing') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
