// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/CodeBlock',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { code: 'echo hi' }
    const el = document.createElement('uni-code-block')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'language',
  render: () => {
    const props: Record<string, unknown> = { code: 'echo hi', language: 'bash', label: 'shell' }
    const el = document.createElement('uni-code-block')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
