// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Selection & menus/ColumnToggle',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "columns": [{ "key": "a", "label": "A", "required": true }, { "key": "b", "label": "B" }], "visible": new Set(["a"]), "onChange": () => {} };
    const el = document.createElement('uni-column-toggle');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
