// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Feedback/ConfirmDialog',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'open info',
  render: () => {
    const props: Record<string, unknown> = {
      open: true,
      title: '?',
      description: 'd',
      onConfirm: () => {},
      onCancel: () => {},
    }
    const el = document.createElement('uni-confirm-dialog') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'open danger',
  render: () => {
    const props: Record<string, unknown> = {
      open: true,
      title: '?',
      variant: 'danger',
      onConfirm: () => {},
      onCancel: () => {},
    }
    const el = document.createElement('uni-confirm-dialog') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'closed',
  render: () => {
    const props: Record<string, unknown> = {
      open: false,
      title: '?',
      onConfirm: () => {},
      onCancel: () => {},
    }
    const el = document.createElement('uni-confirm-dialog') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
