// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Selection & menus/ContextualHelp',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'top',
  render: () => {
    const props: Record<string, unknown> = { title: 't', body: 'b' }
    const el = document.createElement('uni-contextual-help')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'bottom',
  render: () => {
    const props: Record<string, unknown> = { title: 't', body: 'b', placement: 'bottom' }
    const el = document.createElement('uni-contextual-help')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
