// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Selection & menus/ContextMenu',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "open",
  render: () => {
    const props: Record<string, unknown> = { "open": true, "x": 10, "y": 10, "onClose": () => {}, "onAction": () => {}, "items": [{ "id": "a", "label": "A" }, { "id": "b", "label": "B", "danger": true, "disabled": true }] };
    const el = document.createElement('uni-context-menu');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "closed",
  render: () => {
    const props: Record<string, unknown> = { "open": false, "x": 0, "y": 0, "onClose": () => {}, "onAction": () => {}, "items": [] };
    const el = document.createElement('uni-context-menu');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
