// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Feedback/CopyButton',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { text: 'hello' }
    const el = document.createElement('uni-copy-button')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'label',
  render: () => {
    const props: Record<string, unknown> = { text: 'hello', label: 'Copy hello' }
    const el = document.createElement('uni-copy-button')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
