// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: distribution/CorrelationMatrix',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      labels: ['A', 'B'],
      data: [
        [1, 0.4],
        [0.4, 1],
      ],
    }
    const el = document.createElement('uni-correlation-matrix')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
