// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Feedback/CountUp',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { to: 100 }
    const el = document.createElement('uni-count-up')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'options',
  render: () => {
    const props: Record<string, unknown> = {
      from: 10,
      to: 1234,
      duration: 50,
      decimals: 2,
      prefix: '$',
      suffix: '!',
      separator: ',',
    }
    const el = document.createElement('uni-count-up')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'zero',
  render: () => {
    const props: Record<string, unknown> = { to: 0, duration: 0 }
    const el = document.createElement('uni-count-up')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
