// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: distribution/CumulativeDistribution',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "series": [{ "label": "a", "color": "#006FFF", "values": [1, 4, 2, 7, 5, 9] }] };
    const el = document.createElement('uni-cumulative-distribution');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "no guides",
  render: () => {
    const props: Record<string, unknown> = { "series": [{ "label": "a", "color": "#006FFF", "values": [1, 4, 2, 7, 5, 9] }], "guides": [], "unit": "ms" };
    const el = document.createElement('uni-cumulative-distribution');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
