// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Inputs/DatePicker',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {}
    const el = document.createElement('uni-date-picker')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'controlled',
  render: () => {
    const props: Record<string, unknown> = {
      value: new Date('2025-01-01T00:00:00.000Z'),
      onChange: () => {},
    }
    const el = document.createElement('uni-date-picker')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'disabled',
  render: () => {
    const props: Record<string, unknown> = { disabled: true }
    const el = document.createElement('uni-date-picker')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
