// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: hierarchy & flow/Dendrogram',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      root: {
        id: 'r',
        label: 'r',
        children: [
          { id: 'a', label: 'A' },
          { id: 'b', label: 'B', color: '#0f0', children: [{ id: 'b1', label: 'B1' }] },
        ],
      },
    }
    const el = document.createElement('uni-dendrogram') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
