// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: hierarchy & flow/Donut',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      segments: [
        { label: 'A', value: 1, color: '#006FFF' },
        { label: 'B', value: 2, color: '#0f0' },
      ],
      centerValue: 3,
      centerLabel: 'Total',
    }
    const el = document.createElement('uni-donut') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
