// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: comparison/DotPlot',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "items": [{ "label": "A", "value": 5, "compare": 3 }, { "label": "B", "value": 10, "color": "#0f0" }], "unit": "ms", "valueLegend": "now", "compareLegend": "prev" };
    const el = document.createElement('uni-dot-plot');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "no compare",
  render: () => {
    const props: Record<string, unknown> = { "items": [{ "label": "A", "value": 5 }], "max": 20 };
    const el = document.createElement('uni-dot-plot');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
