// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Layout/Drawer',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "open",
  render: () => {
    const props: Record<string, unknown> = { "open": true, "title": "D", "onClose": () => {} };
    const el = document.createElement('uni-drawer');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "hi";
    return el;
  },
};

export const Variant1: Story = {
  name: "closed",
  render: () => {
    const props: Record<string, unknown> = { "open": false, "title": "D", "onClose": () => {} };
    const el = document.createElement('uni-drawer');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
