// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: time-series/DualAxisChart',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "bars": { "label": "b", "color": "#006FFF", "values": [10, 30, 20, 40] }, "line": { "label": "l", "color": "#0f0", "values": [5, 18, 22, 17] }, "labels": ["Mon", "Tue", "Wed", "Thu"] };
    const el = document.createElement('uni-dual-axis-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
