// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: comparison/DumbbellChart',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "items": [{ "label": "A", "start": 1, "end": 9 }, { "label": "B", "start": 4, "end": 6, "color": "#0f0" }], "unit": "ms" };
    const el = document.createElement('uni-dumbbell-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
