// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Inputs/DurationInput',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { label: 'T' }
    const el = document.createElement('uni-duration-input') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'controlled',
  render: () => {
    const props: Record<string, unknown> = { label: 'T', value: 3700, onChange: () => {} }
    const el = document.createElement('uni-duration-input') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'disabled',
  render: () => {
    const props: Record<string, unknown> = { label: 'T', disabled: true, maxHours: 12 }
    const el = document.createElement('uni-duration-input') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
