// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: time-series/ErrorBandChart',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      series: [
        {
          label: 'a',
          color: '#006FFF',
          mean: [1, 2, 3],
          lower: [0.5, 1.5, 2.5],
          upper: [1.5, 2.5, 3.5],
        },
      ],
      xLabels: ['a', 'b', 'c'],
      unit: 'ms',
    }
    const el = document.createElement('uni-error-band-chart')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'fixed',
  render: () => {
    const props: Record<string, unknown> = {
      series: [{ label: 'a', color: '#006FFF', mean: [1], lower: [0], upper: [2] }],
      yRange: [0, 5],
    }
    const el = document.createElement('uni-error-band-chart')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
