// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/ExpandableRow',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'closed',
  render: () => {
    const props: Record<string, unknown> = { colSpan: 1 }
    const el = document.createElement('uni-expandable-row') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'open',
  render: () => {
    const props: Record<string, unknown> = { colSpan: 1, defaultExpanded: true }
    const el = document.createElement('uni-expandable-row') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
