// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Specialised/Field',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "label": "Name" };
    const el = document.createElement('uni-field');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "hint",
  render: () => {
    const props: Record<string, unknown> = { "label": "Name", "hint": "hint", "required": true };
    const el = document.createElement('uni-field');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant2: Story = {
  name: "error",
  render: () => {
    const props: Record<string, unknown> = { "label": "Name", "error": "bad" };
    const el = document.createElement('uni-field');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant3: Story = {
  name: "value",
  render: () => {
    const props: Record<string, unknown> = { "label": "Name", "value": "v" };
    const el = document.createElement('uni-field');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
