// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Selection & menus/FilterBuilder',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      fields: [
        { key: 'name', label: 'Name' },
        { key: 'count', label: 'Count', type: 'number' },
        { key: 'kind', label: 'K', type: 'select', options: ['a', 'b'] },
      ],
    }
    const el = document.createElement('uni-filter-builder') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'with rules',
  render: () => {
    const props: Record<string, unknown> = {
      fields: [{ key: 'name', label: 'Name' }],
      value: [{ id: '1', field: 'name', op: 'is', value: 'foo' }],
      conjunction: 'or',
      onChange: () => {},
    }
    const el = document.createElement('uni-filter-builder') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
