// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: hierarchy & flow/ForceGraph',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      nodes: [
        { id: 'a', label: 'A' },
        { id: 'b', label: 'B', color: '#0f0', r: 8 },
      ],
      links: [{ source: 'a', target: 'b' }],
    }
    const el = document.createElement('uni-force-graph') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
