// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: hierarchy & flow/FunnelChart',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "segments": [{ "label": "a", "value": 100 }, { "label": "b", "value": 60, "color": "#0f0" }, { "label": "c", "value": 20 }] };
    const el = document.createElement('uni-funnel-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
