// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: time-series/GanttChart',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      tasks: [
        { id: '1', label: 'A', start: 0, end: 4 },
        { id: '2', label: 'B', start: 2, end: 6, color: '#0f0' },
      ],
      xLabels: ['Mon', 'Tue', 'Wed', 'Thu'],
    }
    const el = document.createElement('uni-gantt-chart')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
