// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Feedback/Gauge',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { value: 0.5, label: 'cpu' }
    const el = document.createElement('uni-gauge')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'all',
  render: () => {
    const props: Record<string, unknown> = { value: 0.8, label: 'mem', color: '#0f0', size: 80 }
    const el = document.createElement('uni-gauge')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'high',
  render: () => {
    const props: Record<string, unknown> = { value: 1.5, label: 'hot' }
    const el = document.createElement('uni-gauge')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
