// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/GroupedList',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      groups: [
        { title: 'A', items: [{ label: 'one', sublabel: 's', meta: 'm', status: 'ok' }] },
        {
          title: 'B',
          items: [
            { label: 'two', status: 'warn' },
            { label: 'three', status: 'critical' },
          ],
        },
      ],
    }
    const el = document.createElement('uni-grouped-list')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'fixed',
  render: () => {
    const props: Record<string, unknown> = {
      groups: [{ title: 'A', items: [{ label: 'one' }] }],
      collapsible: false,
    }
    const el = document.createElement('uni-grouped-list')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
