// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: distribution/HeatMap',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      data: [
        [0, 0.5, 1],
        [1, 0.5, 0],
      ],
      xLabels: ['x', 'y', 'z'],
    }
    const el = document.createElement('uni-heat-map')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
