// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: distribution/Histogram',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      bins: [
        { x0: 0, x1: 10, count: 5 },
        { x0: 10, x1: 20, count: 8 },
      ],
      xUnit: 'ms',
    }
    const el = document.createElement('uni-histogram')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
