// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: time-series/HorizonChart',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "series": [{ "label": "a", "values": [1, 4, 2, 7, 5, 9] }, { "label": "b", "values": [1, 4, 2, 7, 5, 9], "color": "#0f0" }], "xLabels": ["M", "T", "W", "T", "F", "S"] };
    const el = document.createElement('uni-horizon-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
