// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Feedback/InlineEdit',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "value": "hi", "onConfirm": () => {}, "label": "Name" };
    const el = document.createElement('uni-inline-edit');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "placeholder",
  render: () => {
    const props: Record<string, unknown> = { "value": "", "onConfirm": () => {}, "label": "Name", "placeholder": "..." };
    const el = document.createElement('uni-inline-edit');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
