// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/JsonViewer',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'object',
  render: () => {
    const props: Record<string, unknown> = {
      data: { a: 1, b: [1, 2], c: { d: true, e: null, f: 'x' } },
    }
    const el = document.createElement('uni-json-viewer') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'collapsed',
  render: () => {
    const props: Record<string, unknown> = {
      data: { a: { b: { c: { d: 1 } } } },
      defaultExpanded: false,
      maxDepth: 1,
    }
    const el = document.createElement('uni-json-viewer') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'array',
  render: () => {
    const props: Record<string, unknown> = { data: [1, 2, 3] }
    const el = document.createElement('uni-json-viewer') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant3: Story = {
  name: 'primitive',
  render: () => {
    const props: Record<string, unknown> = { data: 'hi' }
    const el = document.createElement('uni-json-viewer') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
