// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/KanbanBoard',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      columns: [
        {
          id: 'todo',
          title: 'To do',
          color: '#0f0',
          cards: [{ id: '1', title: 'A', subtitle: 's', meta: 'm' }],
        },
        { id: 'done', title: 'Done', cards: [] },
      ],
    }
    const el = document.createElement('uni-kanban-board') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'no cb',
  render: () => {
    const props: Record<string, unknown> = {
      columns: [{ id: 'a', title: 'A', cards: [{ id: '1', title: 't' }] }],
    }
    const el = document.createElement('uni-kanban-board') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
