// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Inputs/Kbd',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'string',
  render: () => {
    const props: Record<string, unknown> = { keys: 'K' }
    const el = document.createElement('uni-kbd')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'array',
  render: () => {
    const props: Record<string, unknown> = { keys: ['Ctrl', 'K'] }
    const el = document.createElement('uni-kbd')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
