// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/LogViewer',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      entries: [
        { time: '00:00', level: 'info', message: 'hi' },
        { time: '00:01', level: 'warn', message: 'w' },
        { time: '00:02', level: 'error', message: 'e', source: 'src' },
        { time: '00:03', level: 'debug', message: 'd' },
      ],
    }
    const el = document.createElement('uni-log-viewer')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'no follow',
  render: () => {
    const props: Record<string, unknown> = { entries: [], defaultFollow: false }
    const el = document.createElement('uni-log-viewer')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
