// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Inputs/MACInput',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { label: 'MAC' }
    const el = document.createElement('uni-macinput') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'controlled',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'MAC',
      value: 'ff:ff:ff:ff:ff:ff',
      onChange: () => {},
    }
    const el = document.createElement('uni-macinput') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'disabled',
  render: () => {
    const props: Record<string, unknown> = { label: 'MAC', disabled: true }
    const el = document.createElement('uni-macinput') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
