// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: comparison/MarimekkoChart',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "columns": [{ "label": "A", "segments": [{ "label": "a", "value": 1 }, { "label": "b", "value": 2, "color": "#0f0" }] }, { "label": "B", "segments": [{ "label": "a", "value": 2 }] }] };
    const el = document.createElement('uni-marimekko-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "empty",
  render: () => {
    const props: Record<string, unknown> = { "columns": [{ "label": "A", "segments": [] }, { "label": "B", "segments": [{ "label": "x", "value": 5 }] }] };
    const el = document.createElement('uni-marimekko-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
