// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Selection & menus/Menubar',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      menus: [
        {
          id: 'f',
          label: 'File',
          items: [
            { id: 'open', label: 'Open' },
            { id: 'sep', label: '', separator: true },
            { id: 'close', label: 'Close', disabled: true },
          ],
        },
        { id: 'e', label: 'Edit', items: [{ id: 'cut', label: 'Cut' }] },
      ],
      onAction: () => {},
    }
    const el = document.createElement('uni-menubar') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
