// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Inputs/MultiSelect',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "options": [{ "value": "a", "label": "A" }, { "value": "b", "label": "B" }], "value": ["a"], "onChange": () => {} };
    const el = document.createElement('uni-multi-select');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "no value",
  render: () => {
    const props: Record<string, unknown> = { "options": [{ "value": "a", "label": "A" }], "label": "lab" };
    const el = document.createElement('uni-multi-select');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant2: Story = {
  name: "disabled",
  render: () => {
    const props: Record<string, unknown> = { "options": [{ "value": "a", "label": "A" }], "disabled": true };
    const el = document.createElement('uni-multi-select');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
