// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Feedback/NotificationPanel',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'open',
  render: () => {
    const props: Record<string, unknown> = {
      open: true,
      onClose: () => {},
      notifications: [
        { id: '1', title: 'hi', body: 'b', time: 'now', read: false, severity: 'info' },
        { id: '2', title: 'h2', body: 'b2', time: 'now', read: true, severity: 'warn' },
        { id: '3', title: 'h3', body: 'b3', time: 'now', read: false, severity: 'critical' },
      ],
      onMarkRead: () => {},
      onMarkAllRead: () => {},
    }
    const el = document.createElement('uni-notification-panel')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'closed',
  render: () => {
    const props: Record<string, unknown> = { open: false, onClose: () => {}, notifications: [] }
    const el = document.createElement('uni-notification-panel')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
