// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Navigation/Pagination',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "page": 1, "pageSize": 10, "total": 50, "onChange": () => {} };
    const el = document.createElement('uni-pagination');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "last",
  render: () => {
    const props: Record<string, unknown> = { "page": 5, "pageSize": 10, "total": 50, "onChange": () => {} };
    const el = document.createElement('uni-pagination');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant2: Story = {
  name: "empty",
  render: () => {
    const props: Record<string, unknown> = { "page": 1, "pageSize": 10, "total": 0, "onChange": () => {} };
    const el = document.createElement('uni-pagination');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
