// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: distribution/ParallelCoordinates',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "axes": [{ "label": "a" }, { "label": "b", "range": [0, 10] }], "series": [{ "label": "s", "values": [1, 5] }, { "label": "s2", "values": [3, 7], "color": "#0f0" }] };
    const el = document.createElement('uni-parallel-coordinates');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
