// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: comparison/ParetoChart',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      items: [
        { label: 'A', value: 50 },
        { label: 'B', value: 30 },
        { label: 'C', value: 20, color: '#0f0' },
      ],
      threshold: 0.7,
    }
    const el = document.createElement('uni-pareto-chart')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
