// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Data display/Pill',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "success",
  render: () => {
    const props: Record<string, unknown> = { "variant": "success" };
    const el = document.createElement('uni-pill');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "ok";
    return el;
  },
};

export const Variant1: Story = {
  name: "warn",
  render: () => {
    const props: Record<string, unknown> = { "variant": "warn" };
    const el = document.createElement('uni-pill');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "w";
    return el;
  },
};

export const Variant2: Story = {
  name: "danger",
  render: () => {
    const props: Record<string, unknown> = { "variant": "danger" };
    const el = document.createElement('uni-pill');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "d";
    return el;
  },
};

export const Variant3: Story = {
  name: "info",
  render: () => {
    const props: Record<string, unknown> = { "variant": "info" };
    const el = document.createElement('uni-pill');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "i";
    return el;
  },
};

export const Variant4: Story = {
  name: "neutral",
  render: () => {
    const props: Record<string, unknown> = {  };
    const el = document.createElement('uni-pill');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "n";
    return el;
  },
};

export const Variant5: Story = {
  name: "no dot",
  render: () => {
    const props: Record<string, unknown> = { "showDot": false };
    const el = document.createElement('uni-pill');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "n";
    return el;
  },
};
