// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: distribution/PolarHeatmap',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      data: [
        { row: 0, col: 0, value: 1 },
        { row: 1, col: 1, value: 0.5 },
      ],
      rows: 2,
      cols: 2,
      colLabels: ['c1', 'c2'],
    }
    const el = document.createElement('uni-polar-heatmap')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
