// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Selection & menus/Popover',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { label: 'open' }
    const el = document.createElement('uni-popover') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v
    el.textContent = 'body'
    return el
  },
}

export const Variant1: Story = {
  name: 'primary',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'open',
      variant: 'primary',
      title: 't',
      placement: 'top',
    }
    const el = document.createElement('uni-popover') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v
    el.textContent = 'body'
    return el
  },
}
