// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: distribution/PunchCard',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      data: [
        [0, 1, 2, 5, 3],
        [2, 1, 0, 4, 2],
        [3, 5, 1, 0, 6],
      ],
      rowLabels: ['r1', 'r2', 'r3'],
      colLabels: ['c1', 'c2', 'c3', 'c4', 'c5'],
    }
    const el = document.createElement('uni-punch-card')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'no labels',
  render: () => {
    const props: Record<string, unknown> = {
      data: [
        [1, 2],
        [3, 4],
      ],
    }
    const el = document.createElement('uni-punch-card')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
