// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: distribution/QuadrantChart',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "points": [{ "x": 1, "y": 4, "label": "a" }, { "x": 9, "y": 9, "label": "b" }, { "x": 1, "y": 1, "label": "c" }, { "x": 9, "y": 1, "label": "d" }], "xThreshold": 5, "yThreshold": 5 };
    const el = document.createElement('uni-quadrant-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "all options",
  render: () => {
    const props: Record<string, unknown> = { "points": [{ "x": 5, "y": 5, "label": "mid" }], "xThreshold": 5, "yThreshold": 5, "xRange": [0, 10], "yRange": [0, 10], "xLabel": "cost", "yLabel": "value" };
    const el = document.createElement('uni-quadrant-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
