// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: comparison/RadarChart',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      series: [{ label: 'a', color: '#006FFF', values: [0.2, 0.5, 0.8, 0.3] }],
      axes: ['a', 'b', 'c', 'd'],
    }
    const el = document.createElement('uni-radar-chart')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
