// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: comparison/RadialBarChart',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      items: [
        { label: 'A', value: 60, max: 100 },
        { label: 'B', value: 80, max: 100, color: '#0f0', unit: '%' },
      ],
    }
    const el = document.createElement('uni-radial-bar-chart') as HTMLElement &
      Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'over',
  render: () => {
    const props: Record<string, unknown> = { items: [{ label: 'A', value: 200, max: 100 }] }
    const el = document.createElement('uni-radial-bar-chart') as HTMLElement &
      Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
