// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Inputs/RangeSlider',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { label: 'R' }
    const el = document.createElement('uni-range-slider') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'controlled',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'R',
      low: 20,
      high: 80,
      onChange: () => {},
      suffix: '%',
    }
    const el = document.createElement('uni-range-slider') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'defaults',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'R',
      defaultLow: 10,
      defaultHigh: 90,
      step: 5,
      disabled: true,
    }
    const el = document.createElement('uni-range-slider') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
