// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/RankedList',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      items: [
        { label: 'A', value: 50, sublabel: 's' },
        { label: 'B', value: 80, color: '#0f0' },
      ],
      unit: 'ms',
    }
    const el = document.createElement('uni-ranked-list') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'fixed',
  render: () => {
    const props: Record<string, unknown> = { items: [{ label: 'A', value: 50 }], max: 100 }
    const el = document.createElement('uni-ranked-list') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
