// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Layout/ResizablePanel',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'vertical',
  render: () => {
    const props: Record<string, unknown> = {}
    const el = document.createElement('uni-resizable-panel')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'horizontal',
  render: () => {
    const props: Record<string, unknown> = {
      orientation: 'horizontal',
      defaultSize: 30,
      min: 10,
      max: 90,
    }
    const el = document.createElement('uni-resizable-panel')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
