// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: distribution/RidgelinePlot',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      series: [
        { label: 'a', values: [1, 4, 2, 7, 5, 9] },
        { label: 'b', values: [1, 4, 2, 7, 5, 9], color: '#0f0' },
      ],
    }
    const el = document.createElement('uni-ridgeline-plot')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'fixed',
  render: () => {
    const props: Record<string, unknown> = {
      series: [{ label: 'a', values: [1, 4, 2, 7, 5, 9] }],
      xRange: [0, 10],
    }
    const el = document.createElement('uni-ridgeline-plot')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
