// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Specialised/RowToggle',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { title: 't', description: 'd', on: false }
    const el = document.createElement('uni-row-toggle')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'on',
  render: () => {
    const props: Record<string, unknown> = {
      title: 't',
      description: 'd',
      on: true,
      onToggle: () => {},
    }
    const el = document.createElement('uni-row-toggle')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
