// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: hierarchy & flow/SankeyDiagram',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      nodes: [
        { id: 'a', label: 'A' },
        { id: 'b', label: 'B', color: '#0f0' },
        { id: 'c', label: 'C' },
      ],
      links: [
        { source: 'a', target: 'b', value: 5 },
        { source: 'b', target: 'c', value: 3 },
      ],
    }
    const el = document.createElement('uni-sankey-diagram') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
