// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: distribution/ScatterPlot',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "points": [{ "x": 1, "y": 4 }, { "x": 2, "y": 9 }, { "x": 3, "y": 6 }, { "x": 4, "y": 8 }] };
    const el = document.createElement('uni-scatter-plot');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "fixed",
  render: () => {
    const props: Record<string, unknown> = { "points": [{ "x": 1, "y": 4 }, { "x": 2, "y": 9 }, { "x": 3, "y": 6 }, { "x": 4, "y": 8 }], "xRange": [0, 10], "yRange": [0, 10] };
    const el = document.createElement('uni-scatter-plot');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
