// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Inputs/SegmentedControl',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'L',
      options: [
        { value: 'a', label: 'A' },
        { value: 'b', label: 'B', disabled: true },
      ],
    }
    const el = document.createElement('uni-segmented-control')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'controlled',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'L',
      options: [
        { value: 'a', label: 'A' },
        { value: 'b', label: 'B' },
      ],
      value: 'b',
      onChange: () => {},
    }
    const el = document.createElement('uni-segmented-control')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'default value',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'L',
      options: [{ value: 'a', label: 'A' }],
      defaultValue: 'a',
    }
    const el = document.createElement('uni-segmented-control')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
