// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Data display/SelectionToolbar',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "count": 3, "actions": [{ "id": "d", "label": "Delete", "danger": true }, { "id": "e", "label": "Edit" }], "onClear": () => {} };
    const el = document.createElement('uni-selection-toolbar');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
