// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Specialised/Sidebar',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "activeId": "dash", "sections": [{ "title": "Manage", "items": [{ "id": "dash", "label": "Dashboard", "count": 3, "pill": 1 }, { "id": "devs", "label": "Devices" }] }], "onChange": () => {} };
    const el = document.createElement('uni-sidebar');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
