// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Feedback/Skeleton',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'text',
  render: () => {
    const props: Record<string, unknown> = {}
    const el = document.createElement('uni-skeleton')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'rect',
  render: () => {
    const props: Record<string, unknown> = { variant: 'rect', width: 100, height: 20 }
    const el = document.createElement('uni-skeleton')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'circle',
  render: () => {
    const props: Record<string, unknown> = { variant: 'circle', width: '40px', height: '40px' }
    const el = document.createElement('uni-skeleton')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
