// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: comparison/SlopeChart',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      items: [
        { label: 'A', before: 5, after: 8 },
        { label: 'B', before: 9, after: 4 },
      ],
      unit: 'ms',
      positiveIsGood: true,
    }
    const el = document.createElement('uni-slope-chart') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'no flag',
  render: () => {
    const props: Record<string, unknown> = {
      items: [
        { label: 'A', before: 5, after: 5 },
        { label: 'B', before: 1, after: 9 },
      ],
    }
    const el = document.createElement('uni-slope-chart') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
