// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Specialised/SortHeader',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "asc active",
  render: () => {
    const props: Record<string, unknown> = { "sortKey": "a", "activeKey": "a", "dir": "asc", "onSort": () => {} };
    const el = document.createElement('uni-sort-header');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "A";
    return el;
  },
};

export const Variant1: Story = {
  name: "desc active",
  render: () => {
    const props: Record<string, unknown> = { "sortKey": "a", "activeKey": "a", "dir": "desc", "onSort": () => {} };
    const el = document.createElement('uni-sort-header');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "A";
    return el;
  },
};

export const Variant2: Story = {
  name: "inactive",
  render: () => {
    const props: Record<string, unknown> = { "sortKey": "a", "activeKey": "b", "dir": "asc", "onSort": () => {} };
    const el = document.createElement('uni-sort-header');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    el.textContent = "A";
    return el;
  },
};
