// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/SortableList',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      items: [
        { id: '1', label: 'A', meta: 'm' },
        { id: '2', label: 'B' },
      ],
      onChange: () => {},
    }
    const el = document.createElement('uni-sortable-list')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'aria',
  render: () => {
    const props: Record<string, unknown> = {
      items: [{ id: '1', label: 'A' }],
      onChange: () => {},
      ariaLabel: 'x',
    }
    const el = document.createElement('uni-sortable-list')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
