// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: time-series/SparklineMatrix',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      rows: [
        { label: 'a', values: [1, 4, 2, 7, 5, 9] },
        {
          label: 'b',
          values: [10, 30, 20, 40],
          color: '#0f0',
          meta: 'm',
          delta: '+1',
          deltaDir: 'up',
        },
        { label: 'c', values: [1, 1], delta: '-1', deltaDir: 'down' },
      ],
    }
    const el = document.createElement('uni-sparkline-matrix')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
