// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Inputs/SplitButton',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'Save',
      items: [
        { id: 'a', label: 'Save as' },
        { id: 'b', label: 'Save copy', disabled: true },
      ],
      onPrimaryClick: () => {},
      onAction: () => {},
    }
    const el = document.createElement('uni-split-button') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'primary',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'x',
      variant: 'primary',
      disabled: true,
      items: [{ id: 'a', label: 'A' }],
    }
    const el = document.createElement('uni-split-button') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'danger',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'x',
      variant: 'danger',
      items: [{ id: 'a', label: 'A' }],
    }
    const el = document.createElement('uni-split-button') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
