// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/Spoiler',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {}
    const el = document.createElement('uni-spoiler')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v
    el.textContent = 'tall'
    return el
  },
}

export const Variant1: Story = {
  name: 'custom',
  render: () => {
    const props: Record<string, unknown> = { maxHeight: 20, showLabel: 'more', hideLabel: 'less' }
    const el = document.createElement('uni-spoiler')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v
    el.textContent = 'x'
    return el
  },
}
