// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Feedback/StackedProgress',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      segments: [
        { label: 'A', value: 30, color: '#006FFF' },
        { label: 'B', value: 60, color: '#0f0' },
      ],
    }
    const el = document.createElement('uni-stacked-progress') as HTMLElement &
      Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'no legend',
  render: () => {
    const props: Record<string, unknown> = {
      segments: [{ label: 'A', value: 50, color: '#006FFF' }],
      total: 200,
      ariaLabel: 'x',
      showLegend: false,
    }
    const el = document.createElement('uni-stacked-progress') as HTMLElement &
      Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
