// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: comparison/StackedBarChart',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "series": [{ "label": "A", "color": "#006FFF", "values": [10, 30, 20, 40] }, { "label": "B", "color": "#00C8C8", "values": [5, 18, 22, 17] }], "labels": ["Mon", "Tue", "Wed", "Thu"] };
    const el = document.createElement('uni-stacked-bar-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "normalised",
  render: () => {
    const props: Record<string, unknown> = { "series": [{ "label": "A", "color": "#006FFF", "values": [10, 30, 20, 40] }, { "label": "B", "color": "#00C8C8", "values": [5, 18, 22, 17] }], "labels": ["Mon", "Tue", "Wed", "Thu"], "normalized": true };
    const el = document.createElement('uni-stacked-bar-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
