// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Inputs/StarRating',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { label: 'rate' }
    const el = document.createElement('uni-star-rating') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'controlled',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'rate',
      value: 3,
      onChange: () => {},
      max: 6,
      size: 'sm',
    }
    const el = document.createElement('uni-star-rating') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'readonly',
  render: () => {
    const props: Record<string, unknown> = { label: 'rate', value: 4, readOnly: true }
    const el = document.createElement('uni-star-rating') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant3: Story = {
  name: 'default value',
  render: () => {
    const props: Record<string, unknown> = { label: 'rate', defaultValue: 2 }
    const el = document.createElement('uni-star-rating') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
