// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Feedback/Stat',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { label: 'L', value: 42 }
    const el = document.createElement('uni-stat')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'all options',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'L',
      value: '42',
      unit: 'ms',
      sub: 'sub',
      delta: '+1',
      deltaDir: 'up',
      span: 2,
      color: '#0f0',
    }
    const el = document.createElement('uni-stat')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'down',
  render: () => {
    const props: Record<string, unknown> = {
      label: 'L',
      value: '42',
      delta: '-1',
      deltaDir: 'down',
    }
    const el = document.createElement('uni-stat')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
