// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: time-series/StepChart',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      series: [
        { label: 'A', color: '#006FFF', values: [10, 30, 20, 40] },
        { label: 'B', color: '#00C8C8', values: [5, 18, 22, 17] },
      ],
      labels: ['Mon', 'Tue', 'Wed', 'Thu'],
    }
    const el = document.createElement('uni-step-chart') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
