// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: time-series/StreamGraph',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      labels: ['Mon', 'Tue', 'Wed', 'Thu'],
      series: [
        { label: 'a', values: [10, 30, 20, 40] },
        { label: 'b', values: [5, 18, 22, 17], color: '#0f0' },
      ],
    }
    const el = document.createElement('uni-stream-graph') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
