// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/SwitchPortGrid',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      ports: [
        { index: 1, status: 'up', speed: '1G' },
        { index: 2, status: 'down', speed: '1G' },
        { index: 3, status: 'disabled', speed: '1G' },
        { index: 4, status: 'poe', speed: '1G' },
        { index: 5, status: 'up', speed: '1G' },
        { index: 6, status: 'down', speed: '1G' },
        { index: 7, status: 'disabled', speed: '1G' },
        { index: 8, status: 'poe', speed: '1G' },
      ],
      columns: 4,
      onPortClick: () => {},
    }
    const el = document.createElement('uni-switch-port-grid') as HTMLElement &
      Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
