// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Specialised/TabPanel',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'active',
  render: () => {
    const props: Record<string, unknown> = { id: 'a', active: 'a' }
    const el = document.createElement('uni-tab-panel') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v
    el.textContent = 'A'
    return el
  },
}

export const Variant1: Story = {
  name: 'inactive',
  render: () => {
    const props: Record<string, unknown> = { id: 'a', active: 'b' }
    const el = document.createElement('uni-tab-panel') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v
    el.textContent = 'A'
    return el
  },
}
