// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Navigation/Tabs',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      items: [
        { id: 'a', label: 'A' },
        { id: 'b', label: 'B' },
      ],
      active: 'a',
      onChange: () => {},
    }
    const el = document.createElement('uni-tabs')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'with aria',
  render: () => {
    const props: Record<string, unknown> = {
      items: [{ id: 'a', label: 'A' }],
      active: 'a',
      ariaLabel: 't',
    }
    const el = document.createElement('uni-tabs')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
