// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: time-series/ThresholdAreaChart',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "values": [1, 4, 2, 7, 5, 9], "labels": ["M", "T", "W", "T", "F", "S"], "threshold": 5, "thresholdLabel": "warn" };
    const el = document.createElement('uni-threshold-area-chart');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
