// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Inputs/Toggle',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'off',
  render: () => {
    const props: Record<string, unknown> = { on: false, ariaLabel: 't' }
    const el = document.createElement('uni-toggle') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'on',
  render: () => {
    const props: Record<string, unknown> = { on: true, onToggle: () => {}, ariaDescribedBy: 'd' }
    const el = document.createElement('uni-toggle') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
