// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Inputs/ToggleGroup',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      options: [
        { value: 'a', label: 'A' },
        { value: 'b', label: 'B', disabled: true },
      ],
      value: ['a'],
      onChange: () => {},
      ariaLabel: 't',
    }
    const el = document.createElement('uni-toggle-group') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'sm',
  render: () => {
    const props: Record<string, unknown> = {
      options: [{ value: 'a', label: 'A' }],
      value: [],
      onChange: () => {},
      ariaLabel: 't',
      size: 'sm',
    }
    const el = document.createElement('uni-toggle-group') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
