// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Selection & menus/Tooltip',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { label: 't' }
    const el = document.createElement('uni-tooltip')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v
    el.textContent = 'x'
    return el
  },
}
