// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Specialised/Topbar',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = { siteName: 'HQ', activeApp: 'network' }
    const el = document.createElement('uni-topbar')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'with apps',
  render: () => {
    const props: Record<string, unknown> = {
      siteName: 'HQ',
      activeApp: 'network',
      onAppChange: () => {},
      initials: 'WB',
      notificationCount: 5,
    }
    const el = document.createElement('uni-topbar')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
