// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/TransferList',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {}
    const el = document.createElement('uni-transfer-list')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'with items',
  render: () => {
    const props: Record<string, unknown> = {
      sourceLabel: 'src',
      targetLabel: 'tgt',
      defaultSource: [{ id: '1', label: 'A', description: 'd' }],
      defaultTarget: [{ id: '2', label: 'B' }],
      onChange: () => {},
    }
    const el = document.createElement('uni-transfer-list')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'controlled',
  render: () => {
    const props: Record<string, unknown> = {
      source: [{ id: '1', label: 'A' }],
      target: [{ id: '2', label: 'B' }],
    }
    const el = document.createElement('uni-transfer-list')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
