// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/TreeBrowser',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      rootId: 'root',
      collections: {
        root: { id: 'root', name: '', collections: ['folder'], items: ['a'] },
        folder: { id: 'folder', name: 'folder', descriptor: '1 item', items: ['b'] },
      },
      items: { a: { id: 'a', name: 'A', descriptor: 'spec' }, b: { id: 'b', name: 'B' } },
      defaultExpanded: ['folder'],
      selected: 'a',
      onselect: () => {},
      label: 'Files',
    }
    const el = document.createElement('uni-tree-browser') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'deep nesting',
  render: () => {
    const props: Record<string, unknown> = {
      rootId: 'root',
      collections: {
        root: { id: 'root', name: '', collections: ['docs'] },
        docs: { id: 'docs', name: 'docs', collections: ['spec'], items: ['readme'] },
        spec: { id: 'spec', name: 'spec', descriptor: '2 files', items: ['rules', 'interface'] },
      },
      items: {
        readme: { id: 'readme', name: 'README' },
        rules: { id: 'rules', name: 'RULES' },
        interface: { id: 'interface', name: 'INTERFACE' },
      },
      defaultExpanded: ['docs', 'spec'],
      label: 'Docs',
    }
    const el = document.createElement('uni-tree-browser') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant2: Story = {
  name: 'controlled expansion',
  render: () => {
    const props: Record<string, unknown> = {
      rootId: 'root',
      collections: {
        root: { id: 'root', name: '', collections: ['folder'] },
        folder: { id: 'folder', name: 'folder', items: ['a'] },
      },
      items: { a: { id: 'a', name: 'A' } },
      expanded: ['folder'],
      ontoggle: () => {},
      label: 'Files',
    }
    const el = document.createElement('uni-tree-browser') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}

export const Variant3: Story = {
  name: 'empty',
  render: () => {
    const props: Record<string, unknown> = {
      rootId: 'root',
      collections: { root: { id: 'root', name: '' } },
    }
    const el = document.createElement('uni-tree-browser') as HTMLElement & Record<string, unknown>
    for (const [k, v] of Object.entries(props)) el[k] = v

    return el
  },
}
