// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Data display/TreeView',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      nodes: [
        { id: 'a', label: 'A', children: [{ id: 'b', label: 'B', icon: 'x', meta: 'm' }] },
        { id: 'c', label: 'C' },
      ],
      defaultExpanded: ['a'],
      selected: 'b',
      onSelect: () => {},
      label: 'L',
    }
    const el = document.createElement('uni-tree-view')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'flat',
  render: () => {
    const props: Record<string, unknown> = { nodes: [{ id: 'a', label: 'A' }] }
    const el = document.createElement('uni-tree-view')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
