// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: time-series/UptimeTimeline',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "series": [{ "label": "A", "segments": [{ "from": 0, "to": 5, "status": "up" }, { "from": 5, "to": 8, "status": "degraded" }, { "from": 8, "to": 10, "status": "down" }] }], "xLabels": ["0", "5", "10"] };
    const el = document.createElement('uni-uptime-timeline');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
