// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: hierarchy & flow/VennDiagram',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'two sets',
  render: () => {
    const props: Record<string, unknown> = {
      sets: [
        { label: 'A', size: 10 },
        { label: 'B', size: 8 },
      ],
      intersections: [{ sets: ['A', 'B'], size: 3 }],
    }
    const el = document.createElement('uni-venn-diagram')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}

export const Variant1: Story = {
  name: 'three sets',
  render: () => {
    const props: Record<string, unknown> = {
      sets: [
        { label: 'A', size: 10, color: '#0f0' },
        { label: 'B', size: 8 },
        { label: 'C', size: 6 },
      ],
    }
    const el = document.createElement('uni-venn-diagram')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
