// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: distribution/ViolinPlot',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "series": [{ "label": "A", "values": [1, 2, 2, 3, 4, 5, 5, 6] }, { "label": "B", "values": [2, 3, 3, 4, 5], "color": "#0f0" }] };
    const el = document.createElement('uni-violin-plot');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "yRange",
  render: () => {
    const props: Record<string, unknown> = { "series": [{ "label": "A", "values": [1, 2, 3] }], "yRange": [0, 10] };
    const el = document.createElement('uni-violin-plot');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
