// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components'

const meta: Meta = {
  title: 'Charts: hierarchy & flow/WaterfallChart',
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  render: () => {
    const props: Record<string, unknown> = {
      bars: [
        { label: 'a', value: 10, kind: 'start' },
        { label: 'b', value: 5, kind: 'pos' },
        { label: 'c', value: -3, kind: 'neg' },
        { label: 'd', value: 12, kind: 'end' },
      ],
    }
    const el = document.createElement('uni-waterfall-chart')
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v

    return el
  },
}
