// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: 'Charts: distribution/WordCloud',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  render: () => {
    const props: Record<string, unknown> = { "items": [{ "word": "w0", "weight": 1 }, { "word": "w1", "weight": 2 }, { "word": "w2", "weight": 3 }, { "word": "w3", "weight": 4 }, { "word": "w4", "weight": 5 }, { "word": "w5", "weight": 1 }, { "word": "w6", "weight": 2 }, { "word": "w7", "weight": 3 }, { "word": "w8", "weight": 4 }, { "word": "w9", "weight": 5 }, { "word": "w10", "weight": 1 }, { "word": "w11", "weight": 2 }, { "word": "w12", "weight": 3 }, { "word": "w13", "weight": 4 }, { "word": "w14", "weight": 5 }, { "word": "w15", "weight": 1 }, { "word": "w16", "weight": 2 }, { "word": "w17", "weight": 3 }, { "word": "w18", "weight": 4 }, { "word": "w19", "weight": 5 }, { "word": "w20", "weight": 1 }, { "word": "w21", "weight": 2 }, { "word": "w22", "weight": 3 }, { "word": "w23", "weight": 4 }, { "word": "w24", "weight": 5 }] };
    const el = document.createElement('uni-word-cloud');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};

export const Variant1: Story = {
  name: "colored",
  render: () => {
    const props: Record<string, unknown> = { "items": [{ "word": "a", "weight": 1, "color": "#0f0" }, { "word": "b", "weight": 5 }] };
    const el = document.createElement('uni-word-cloud');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    
    return el;
  },
};
