// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { AccordionItem } from '@w5-ui/svelte'

const meta = {
  title: 'Specialised/AccordionItem',
  component: AccordionItem,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof AccordionItem>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'closed',
  args: { title: 'T' },
}

export const Variant1: Story = {
  name: 'open',
  args: { title: 'T', defaultOpen: true },
}
