// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ActionMenu } from '@w5-ui/svelte'

const meta = {
  title: 'Selection & menus/ActionMenu',
  component: ActionMenu,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof ActionMenu>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    items: [
      { id: 'a', label: 'A' },
      { id: 'b', label: 'B', danger: true, disabled: true },
    ],
    onAction: () => {},
  },
}
