// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ActivityFeed } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Feedback/ActivityFeed',
  component: ActivityFeed as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: { items: [{ id: '1', title: 'Joined', time: 'now' }] },
}

export const Variant1: Story = {
  name: 'busy',
  args: {
    items: [{ id: '1', title: 'x', description: 'd', time: 'now', severity: 'warn' }],
    busy: true,
    autoScroll: true,
  },
}

export const Variant2: Story = {
  name: 'empty',
  args: { items: [] },
}
