// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { AnnotatedTimeSeries } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: time-series/AnnotatedTimeSeries',
  component: AnnotatedTimeSeries,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof AnnotatedTimeSeries>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    data: [1, 4, 2, 7, 5, 9],
    labels: ['M', 'T', 'W', 'T', 'F', 'S'],
    annotations: [{ index: 2, label: 's' }],
  },
}

export const Variant1: Story = {
  name: 'no annotations',
  args: { data: [1, 4, 2, 7, 5, 9] },
}
