// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { AnnotatedTimeSeries } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: time-series/AnnotatedTimeSeries',
  component: AnnotatedTimeSeries as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "data": [1, 4, 2, 7, 5, 9], "labels": ["M", "T", "W", "T", "F", "S"], "annotations": [{ "index": 2, "label": "s" }] },
};

export const Variant1: Story = {
  name: "no annotations",
  args: { "data": [1, 4, 2, 7, 5, 9] },
};
