// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { AppLayout } from '@w5-ui/svelte'

const meta = {
  title: 'Layout/AppLayout',
  component: AppLayout,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof AppLayout>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { pageLabel: 'Dashboard' },
}
