// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { ArcDiagram } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: hierarchy & flow/ArcDiagram',
  component: ArcDiagram as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "nodes": [{ "id": "a", "label": "A" }, { "id": "b", "label": "B" }, { "id": "c", "label": "C" }], "links": [{ "source": "a", "target": "c", "value": 2 }, { "source": "b", "target": "c" }] },
};
