// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { AreaChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: time-series/AreaChart',
  component: AreaChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof AreaChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    series: [
      { label: 'A', color: '#006FFF', values: [10, 30, 20, 40] },
      { label: 'B', color: '#00C8C8', values: [5, 18, 22, 17] },
    ],
    labels: ['Mon', 'Tue', 'Wed', 'Thu'],
  },
}
