// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Avatar } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/Avatar',
  component: Avatar,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Avatar>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'initials',
  args: { initials: 'WB' },
}

export const Variant1: Story = {
  name: 'image',
  args: { src: 'data:image/svg+xml,<svg/>', alt: 'me', size: 'lg', status: 'online' },
}

export const Variant2: Story = {
  name: 'away',
  args: { status: 'away' },
}

export const Variant3: Story = {
  name: 'sm',
  args: { size: 'sm' },
}
