// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Avatar } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Data display/Avatar',
  component: Avatar as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "initials",
  args: { "initials": "WB" },
};

export const Variant1: Story = {
  name: "image",
  args: { "src": "data:image/svg+xml,<svg/>", "alt": "me", "size": "lg", "status": "online" },
};

export const Variant2: Story = {
  name: "away",
  args: { "status": "away" },
};

export const Variant3: Story = {
  name: "sm",
  args: { "size": "sm" },
};
