// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { AvatarGroup } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Data display/AvatarGroup',
  component: AvatarGroup as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "avatars": [{ "initials": "A" }, { "initials": "B" }] },
};

export const Variant1: Story = {
  name: "overflow",
  args: { "avatars": [{ "initials": "A" }, { "initials": "B" }, { "initials": "C" }, { "initials": "D" }], "max": 2, "size": "sm" },
};
