// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Badge } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/Badge',
  component: Badge,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Badge>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'count',
  args: { count: 3 },
}

export const Variant1: Story = {
  name: 'overflow',
  args: { count: 200, max: 99 },
}

export const Variant2: Story = {
  name: 'showZero',
  args: { count: 0, showZero: true, color: 'info' },
}

export const Variant3: Story = {
  name: 'dot',
  args: { dot: true, color: 'success' },
}
