// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Banner } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Feedback/Banner',
  component: Banner as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "info",
  args: {  },
};

export const Variant1: Story = {
  name: "success",
  args: { "variant": "success", "title": "Done", "action": { "label": "Undo", "onClick": () => {} }, "onDismiss": () => {} },
};

export const Variant2: Story = {
  name: "warn",
  args: { "variant": "warn" },
};

export const Variant3: Story = {
  name: "danger",
  args: { "variant": "danger" },
};
