// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Banner } from '@w5-ui/svelte'

const meta = {
  title: 'Feedback/Banner',
  component: Banner,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Banner>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'info',
  args: {},
}

export const Variant1: Story = {
  name: 'success',
  args: {
    variant: 'success',
    title: 'Done',
    action: { label: 'Undo', onClick: () => {} },
    onDismiss: () => {},
  },
}

export const Variant2: Story = {
  name: 'warn',
  args: { variant: 'warn' },
}

export const Variant3: Story = {
  name: 'danger',
  args: { variant: 'danger' },
}
