// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { BeeswarmChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: distribution/BeeswarmChart',
  component: BeeswarmChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof BeeswarmChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    series: [
      { label: 'A', points: [1, 2, 3] },
      { label: 'B', points: [2, 5, 6], color: '#0f0' },
    ],
    unit: 'ms',
  },
}

export const Variant1: Story = {
  name: 'yRange',
  args: { series: [{ label: 'A', points: [1, 2] }], yRange: [0, 10] },
}
