// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { BoxPlot } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: distribution/BoxPlot',
  component: BoxPlot as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "series": [{ "label": "A", "q0": 1, "q1": 3, "q2": 5, "q3": 7, "q4": 9 }, { "label": "B", "q0": 0, "q1": 2, "q2": 4, "q3": 6, "q4": 8, "color": "#0f0" }] },
};

export const Variant1: Story = {
  name: "yRange",
  args: { "series": [{ "label": "A", "q0": 0, "q1": 2, "q2": 4, "q3": 6, "q4": 8 }], "yRange": [0, 10] },
};
