// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Breadcrumb } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Navigation/Breadcrumb',
  component: Breadcrumb as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: { items: [{ label: 'Home', href: '/' }, { label: 'Now' }], onNavigate: () => {} },
}
