// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { BubbleChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: distribution/BubbleChart',
  component: BubbleChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "points": [{ "x": 1, "y": 2, "r": 5 }, { "x": 4, "y": 7, "r": 10, "color": "#0f0" }] },
};

export const Variant1: Story = {
  name: "fixed",
  args: { "points": [{ "x": 1, "y": 2, "r": 5 }], "xRange": [0, 10], "yRange": [0, 10] },
};
