// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { BubbleChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: distribution/BubbleChart',
  component: BubbleChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof BubbleChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    points: [
      { x: 1, y: 2, r: 5 },
      { x: 4, y: 7, r: 10, color: '#0f0' },
    ],
  },
}

export const Variant1: Story = {
  name: 'fixed',
  args: { points: [{ x: 1, y: 2, r: 5 }], xRange: [0, 10], yRange: [0, 10] },
}
