// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { BulletChart } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Charts: comparison/BulletChart',
  component: BulletChart as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    items: [
      { label: 'A', value: 60, target: 80, ranges: [40, 70], unit: '%' },
      { label: 'B', value: 100, color: '#0f0' },
    ],
  },
}
