// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { BumpChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: comparison/BumpChart',
  component: BumpChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof BumpChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    labels: ['Mon', 'Tue', 'Wed', 'Thu'],
    series: [
      { label: 'A', ranks: [1, 2, 1, 3] },
      { label: 'B', ranks: [2, 1, 3, 1], color: '#0f0' },
    ],
  },
}
