// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Button } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/Button',
  component: Button,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Button>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'ghost',
  args: {},
}

export const Variant1: Story = {
  name: 'primary',
  args: { variant: 'primary' },
}

export const Variant2: Story = {
  name: 'danger',
  args: { variant: 'danger' },
}

export const Variant3: Story = {
  name: 'iconOnly',
  args: { iconOnly: true, title: 'x' },
}

export const Variant4: Story = {
  name: 'loading',
  args: { loading: true },
}

export const Variant5: Story = {
  name: 'disabled',
  args: { disabled: true },
}
