// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { CandlestickChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: time-series/CandlestickChart',
  component: CandlestickChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "bars": [{ "open": 10, "close": 12, "high": 14, "low": 9 }, { "open": 12, "close": 11, "high": 13, "low": 10 }] },
};

export const Variant1: Story = {
  name: "yRange",
  args: { "bars": [{ "open": 1, "close": 2, "high": 3, "low": 0 }], "yRange": [0, 5], "unit": "$" },
};
