// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Card } from '@w5-ui/svelte'

const meta = {
  title: 'Layout/Card',
  component: Card,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Card>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {},
}

export const Variant1: Story = {
  name: 'span',
  args: { span: 2 },
}
