// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Carousel } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Layout/Carousel',
  component: Carousel as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    label: 'news',
    slides: [
      { id: '1', title: 'A', body: 'a' },
      { id: '2', title: 'B', body: 'b' },
    ],
  },
}
