// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Checkbox } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/Checkbox',
  component: Checkbox,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Checkbox>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { label: 'agree' },
}

export const Variant1: Story = {
  name: 'indeterminate',
  args: { label: 'agree', indeterminate: true },
}

export const Variant2: Story = {
  name: 'no label',
  args: {},
}
