// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Checkbox } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/Checkbox',
  component: Checkbox as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "label": "agree" },
};

export const Variant1: Story = {
  name: "indeterminate",
  args: { "label": "agree", "indeterminate": true },
};

export const Variant2: Story = {
  name: "no label",
  args: {  },
};
