// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ChordDiagram } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: hierarchy & flow/ChordDiagram',
  component: ChordDiagram,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof ChordDiagram>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    nodes: [{ label: 'A' }, { label: 'B', color: '#0f0' }, { label: 'C' }],
    matrix: [
      [0, 5, 2],
      [5, 0, 1],
      [2, 1, 0],
    ],
  },
}
