// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { CIDRInput } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/CIDRInput',
  component: CIDRInput as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "label": "C" },
};

export const Variant1: Story = {
  name: "controlled",
  args: { "label": "C", "value": "10.0.0.0/8", "onChange": () => {} },
};

export const Variant2: Story = {
  name: "disabled",
  args: { "label": "C", "disabled": true },
};
