// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { CirclePacking } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: hierarchy & flow/CirclePacking',
  component: CirclePacking,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof CirclePacking>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    items: [
      { id: 'a', label: 'A', value: 10 },
      { id: 'b', label: 'B', value: 20, color: '#0f0' },
    ],
  },
}

export const Variant1: Story = {
  name: 'many',
  args: {
    items: [
      { id: '0', label: 'n0', value: 100 },
      { id: '1', label: 'n1', value: 92 },
      { id: '2', label: 'n2', value: 84 },
      { id: '3', label: 'n3', value: 76 },
      { id: '4', label: 'n4', value: 68 },
      { id: '5', label: 'n5', value: 60 },
      { id: '6', label: 'n6', value: 52 },
      { id: '7', label: 'n7', value: 44 },
    ],
  },
}

export const Variant2: Story = {
  name: 'empty',
  args: { items: [] },
}
