// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { CodeBlock } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Data display/CodeBlock',
  component: CodeBlock as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "code": "echo hi" },
};

export const Variant1: Story = {
  name: "language",
  args: { "code": "echo hi", "language": "bash", "label": "shell" },
};
