// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { CodeBlock } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/CodeBlock',
  component: CodeBlock,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof CodeBlock>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { code: 'echo hi' },
}

export const Variant1: Story = {
  name: 'language',
  args: { code: 'echo hi', language: 'bash', label: 'shell' },
}
