// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { ColorPicker } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/ColorPicker',
  component: ColorPicker as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: {  },
};

export const Variant1: Story = {
  name: "controlled",
  args: { "value": "#006FFF", "onChange": () => {}, "srOnlyLabel": true },
};

export const Variant2: Story = {
  name: "disabled",
  args: { "disabled": true },
};
