// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ColorPicker } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/ColorPicker',
  component: ColorPicker,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof ColorPicker>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {},
}

export const Variant1: Story = {
  name: 'controlled',
  args: { value: '#006FFF', onChange: () => {}, srOnlyLabel: true },
}

export const Variant2: Story = {
  name: 'disabled',
  args: { disabled: true },
}
