// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ColumnToggle } from '@w5-ui/svelte'

const meta = {
  title: 'Selection & menus/ColumnToggle',
  component: ColumnToggle,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof ColumnToggle>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    columns: [
      { key: 'a', label: 'A', required: true },
      { key: 'b', label: 'B' },
    ],
    visible: new Set(['a']),
    onChange: () => {},
  },
}
