// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Combobox } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/Combobox',
  component: Combobox,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Combobox>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    label: 'Pick',
    options: [
      { value: 'a', label: 'A' },
      { value: 'b', label: 'B' },
    ],
    value: 'a',
    onChange: () => {},
  },
}

export const Variant1: Story = {
  name: 'no value',
  args: { options: [{ value: 'a', label: 'A' }] },
}

export const Variant2: Story = {
  name: 'disabled',
  args: { options: [{ value: 'a', label: 'A' }], disabled: true },
}
