// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { CommandPalette } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Selection & menus/CommandPalette',
  component: CommandPalette as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "open",
  args: { "open": true, "onClose": () => {}, "items": [{ "id": "a", "label": "A", "group": "P", "shortcut": "A" }, { "id": "b", "label": "B" }], "onSelect": () => {} },
};

export const Variant1: Story = {
  name: "closed",
  args: { "open": false, "onClose": () => {}, "items": [], "onSelect": () => {} },
};
