// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { CommandPalette } from '@w5-ui/svelte'

const meta = {
  title: 'Selection & menus/CommandPalette',
  component: CommandPalette,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof CommandPalette>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'open',
  args: {
    open: true,
    onClose: () => {},
    items: [
      { id: 'a', label: 'A', group: 'P', shortcut: 'A' },
      { id: 'b', label: 'B' },
    ],
    onSelect: () => {},
  },
}

export const Variant1: Story = {
  name: 'closed',
  args: { open: false, onClose: () => {}, items: [], onSelect: () => {} },
}
