// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ConfirmDialog } from '@w5-ui/svelte'

const meta = {
  title: 'Feedback/ConfirmDialog',
  component: ConfirmDialog,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof ConfirmDialog>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'open info',
  args: { open: true, title: '?', description: 'd', onConfirm: () => {}, onCancel: () => {} },
}

export const Variant1: Story = {
  name: 'open danger',
  args: { open: true, title: '?', variant: 'danger', onConfirm: () => {}, onCancel: () => {} },
}

export const Variant2: Story = {
  name: 'closed',
  args: { open: false, title: '?', onConfirm: () => {}, onCancel: () => {} },
}
