// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ContourPlot } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: distribution/ContourPlot',
  component: ContourPlot,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof ContourPlot>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    points: [
      { x: 1, y: 4 },
      { x: 2, y: 9 },
      { x: 3, y: 6 },
      { x: 4, y: 8 },
    ],
  },
}

export const Variant1: Story = {
  name: 'fixed',
  args: {
    points: [
      { x: 1, y: 4 },
      { x: 2, y: 9 },
      { x: 3, y: 6 },
      { x: 4, y: 8 },
    ],
    xRange: [0, 10],
    yRange: [0, 10],
  },
}
