// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ContextMenu } from '@w5-ui/svelte'

const meta = {
  title: 'Selection & menus/ContextMenu',
  component: ContextMenu,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof ContextMenu>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'open',
  args: {
    open: true,
    x: 10,
    y: 10,
    onClose: () => {},
    onAction: () => {},
    items: [
      { id: 'a', label: 'A' },
      { id: 'b', label: 'B', danger: true, disabled: true },
    ],
  },
}

export const Variant1: Story = {
  name: 'closed',
  args: { open: false, x: 0, y: 0, onClose: () => {}, onAction: () => {}, items: [] },
}
