// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ContextualHelp } from '@w5-ui/svelte'

const meta = {
  title: 'Selection & menus/ContextualHelp',
  component: ContextualHelp,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof ContextualHelp>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'top',
  args: { title: 't', body: 'b' },
}

export const Variant1: Story = {
  name: 'bottom',
  args: { title: 't', body: 'b', placement: 'bottom' },
}
