// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { ContextualHelp } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Selection & menus/ContextualHelp',
  component: ContextualHelp as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "top",
  args: { "title": "t", "body": "b" },
};

export const Variant1: Story = {
  name: "bottom",
  args: { "title": "t", "body": "b", "placement": "bottom" },
};
