// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { CopyButton } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Feedback/CopyButton',
  component: CopyButton as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "text": "hello" },
};

export const Variant1: Story = {
  name: "label",
  args: { "text": "hello", "label": "Copy hello" },
};
