// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { CopyButton } from '@w5-ui/svelte'

const meta = {
  title: 'Feedback/CopyButton',
  component: CopyButton,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof CopyButton>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { text: 'hello' },
}

export const Variant1: Story = {
  name: 'label',
  args: { text: 'hello', label: 'Copy hello' },
}
