// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { CorrelationMatrix } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: distribution/CorrelationMatrix',
  component: CorrelationMatrix as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "labels": ["A", "B"], "data": [[1, 0.4], [0.4, 1]] },
};
