// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { CorrelationMatrix } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: distribution/CorrelationMatrix',
  component: CorrelationMatrix,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof CorrelationMatrix>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    labels: ['A', 'B'],
    data: [
      [1, 0.4],
      [0.4, 1],
    ],
  },
}
