// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { CountUp } from '@w5-ui/svelte'

const meta = {
  title: 'Feedback/CountUp',
  component: CountUp,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof CountUp>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { to: 100 },
}

export const Variant1: Story = {
  name: 'options',
  args: { from: 10, to: 1234, duration: 50, decimals: 2, prefix: '$', suffix: '!', separator: ',' },
}

export const Variant2: Story = {
  name: 'zero',
  args: { to: 0, duration: 0 },
}
