// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { CumulativeDistribution } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: distribution/CumulativeDistribution',
  component: CumulativeDistribution,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof CumulativeDistribution>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { series: [{ label: 'a', color: '#006FFF', values: [1, 4, 2, 7, 5, 9] }] },
}

export const Variant1: Story = {
  name: 'no guides',
  args: {
    series: [{ label: 'a', color: '#006FFF', values: [1, 4, 2, 7, 5, 9] }],
    guides: [],
    unit: 'ms',
  },
}
