// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { CumulativeDistribution } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: distribution/CumulativeDistribution',
  component: CumulativeDistribution as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "series": [{ "label": "a", "color": "#006FFF", "values": [1, 4, 2, 7, 5, 9] }] },
};

export const Variant1: Story = {
  name: "no guides",
  args: { "series": [{ "label": "a", "color": "#006FFF", "values": [1, 4, 2, 7, 5, 9] }], "guides": [], "unit": "ms" },
};
