// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { DateRangePicker } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/DateRangePicker',
  component: DateRangePicker,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof DateRangePicker>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {},
}

export const Variant1: Story = {
  name: 'controlled',
  args: {
    value: {
      start: new Date('2025-01-01T00:00:00.000Z'),
      end: new Date('2025-01-10T00:00:00.000Z'),
    },
    onChange: () => {},
  },
}

export const Variant2: Story = {
  name: 'disabled',
  args: { disabled: true },
}
