// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { DateRangePicker } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/DateRangePicker',
  component: DateRangePicker as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: {  },
};

export const Variant1: Story = {
  name: "controlled",
  args: { "value": { "start": new Date("2025-01-01T00:00:00.000Z"), "end": new Date("2025-01-10T00:00:00.000Z") }, "onChange": () => {} },
};

export const Variant2: Story = {
  name: "disabled",
  args: { "disabled": true },
};
