// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Dendrogram } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: hierarchy & flow/Dendrogram',
  component: Dendrogram as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "root": { "id": "r", "label": "r", "children": [{ "id": "a", "label": "A" }, { "id": "b", "label": "B", "color": "#0f0", "children": [{ "id": "b1", "label": "B1" }] }] } },
};
