// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Donut } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: hierarchy & flow/Donut',
  component: Donut as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "segments": [{ "label": "A", "value": 1, "color": "#006FFF" }, { "label": "B", "value": 2, "color": "#0f0" }], "centerValue": 3, "centerLabel": "Total" },
};
