// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Donut } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: hierarchy & flow/Donut',
  component: Donut,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Donut>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    segments: [
      { label: 'A', value: 1, color: '#006FFF' },
      { label: 'B', value: 2, color: '#0f0' },
    ],
    centerValue: 3,
    centerLabel: 'Total',
  },
}
