// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { DotPlot } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: comparison/DotPlot',
  component: DotPlot,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof DotPlot>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    items: [
      { label: 'A', value: 5, compare: 3 },
      { label: 'B', value: 10, color: '#0f0' },
    ],
    unit: 'ms',
    valueLegend: 'now',
    compareLegend: 'prev',
  },
}

export const Variant1: Story = {
  name: 'no compare',
  args: { items: [{ label: 'A', value: 5 }], max: 20 },
}
