// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { DualAxisChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: time-series/DualAxisChart',
  component: DualAxisChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof DualAxisChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    bars: { label: 'b', color: '#006FFF', values: [10, 30, 20, 40] },
    line: { label: 'l', color: '#0f0', values: [5, 18, 22, 17] },
    labels: ['Mon', 'Tue', 'Wed', 'Thu'],
  },
}
