// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { DumbbellChart } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Charts: comparison/DumbbellChart',
  component: DumbbellChart as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    items: [
      { label: 'A', start: 1, end: 9 },
      { label: 'B', start: 4, end: 6, color: '#0f0' },
    ],
    unit: 'ms',
  },
}
