// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { DurationInput } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/DurationInput',
  component: DurationInput as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "label": "T" },
};

export const Variant1: Story = {
  name: "controlled",
  args: { "label": "T", "value": 3700, "onChange": () => {} },
};

export const Variant2: Story = {
  name: "disabled",
  args: { "label": "T", "disabled": true, "maxHours": 12 },
};
