// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { DurationInput } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/DurationInput',
  component: DurationInput,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof DurationInput>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { label: 'T' },
}

export const Variant1: Story = {
  name: 'controlled',
  args: { label: 'T', value: 3700, onChange: () => {} },
}

export const Variant2: Story = {
  name: 'disabled',
  args: { label: 'T', disabled: true, maxHours: 12 },
}
