// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { EmptyState } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Feedback/EmptyState',
  component: EmptyState as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "title": "Nothing" },
};

export const Variant1: Story = {
  name: "with action",
  args: { "title": "N", "description": "d" },
};
