// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ErrorBandChart } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Charts: time-series/ErrorBandChart',
  component: ErrorBandChart as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    series: [
      {
        label: 'a',
        color: '#006FFF',
        mean: [1, 2, 3],
        lower: [0.5, 1.5, 2.5],
        upper: [1.5, 2.5, 3.5],
      },
    ],
    xLabels: ['a', 'b', 'c'],
    unit: 'ms',
  },
}

export const Variant1: Story = {
  name: 'fixed',
  args: {
    series: [{ label: 'a', color: '#006FFF', mean: [1], lower: [0], upper: [2] }],
    yRange: [0, 5],
  },
}
