// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ExpandableRow } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/ExpandableRow',
  component: ExpandableRow,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof ExpandableRow>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'closed',
  args: { colSpan: 1 },
}

export const Variant1: Story = {
  name: 'open',
  args: { colSpan: 1, defaultExpanded: true },
}
