// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { ExpandableRow } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Data display/ExpandableRow',
  component: ExpandableRow as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "closed",
  args: { "colSpan": 1 },
};

export const Variant1: Story = {
  name: "open",
  args: { "colSpan": 1, "defaultExpanded": true },
};
