// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Field } from '@w5-ui/svelte'

const meta = {
  title: 'Specialised/Field',
  component: Field,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Field>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { label: 'Name' },
}

export const Variant1: Story = {
  name: 'hint',
  args: { label: 'Name', hint: 'hint', required: true },
}

export const Variant2: Story = {
  name: 'error',
  args: { label: 'Name', error: 'bad' },
}

export const Variant3: Story = {
  name: 'value',
  args: { label: 'Name', value: 'v' },
}
