// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Field } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Specialised/Field',
  component: Field as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "label": "Name" },
};

export const Variant1: Story = {
  name: "hint",
  args: { "label": "Name", "hint": "hint", "required": true },
};

export const Variant2: Story = {
  name: "error",
  args: { "label": "Name", "error": "bad" },
};

export const Variant3: Story = {
  name: "value",
  args: { "label": "Name", "value": "v" },
};
