// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { FileUpload } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/FileUpload',
  component: FileUpload,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof FileUpload>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {},
}

export const Variant1: Story = {
  name: 'multiple',
  args: { label: 'Logo', hint: 'png', accept: '.png', multiple: true, onFiles: () => {} },
}

export const Variant2: Story = {
  name: 'disabled',
  args: { disabled: true },
}
