// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { FilterBuilder } from '@w5-ui/svelte'

const meta = {
  title: 'Selection & menus/FilterBuilder',
  component: FilterBuilder,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof FilterBuilder>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    fields: [
      { key: 'name', label: 'Name' },
      { key: 'count', label: 'Count', type: 'number' },
      { key: 'kind', label: 'K', type: 'select', options: ['a', 'b'] },
    ],
  },
}

export const Variant1: Story = {
  name: 'with rules',
  args: {
    fields: [{ key: 'name', label: 'Name' }],
    value: [{ id: '1', field: 'name', op: 'is', value: 'foo' }],
    conjunction: 'or',
    onChange: () => {},
  },
}
