// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ForceGraph } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: hierarchy & flow/ForceGraph',
  component: ForceGraph,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof ForceGraph>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    nodes: [
      { id: 'a', label: 'A' },
      { id: 'b', label: 'B', color: '#0f0', r: 8 },
    ],
    links: [{ source: 'a', target: 'b' }],
  },
}
