// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { FunnelChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: hierarchy & flow/FunnelChart',
  component: FunnelChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "segments": [{ "label": "a", "value": 100 }, { "label": "b", "value": 60, "color": "#0f0" }, { "label": "c", "value": 20 }] },
};
