// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { FunnelChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: hierarchy & flow/FunnelChart',
  component: FunnelChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof FunnelChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    segments: [
      { label: 'a', value: 100 },
      { label: 'b', value: 60, color: '#0f0' },
      { label: 'c', value: 20 },
    ],
  },
}
