// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { GanttChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: time-series/GanttChart',
  component: GanttChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "tasks": [{ "id": "1", "label": "A", "start": 0, "end": 4 }, { "id": "2", "label": "B", "start": 2, "end": 6, "color": "#0f0" }], "xLabels": ["Mon", "Tue", "Wed", "Thu"] },
};
