// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { GanttChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: time-series/GanttChart',
  component: GanttChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof GanttChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    tasks: [
      { id: '1', label: 'A', start: 0, end: 4 },
      { id: '2', label: 'B', start: 2, end: 6, color: '#0f0' },
    ],
    xLabels: ['Mon', 'Tue', 'Wed', 'Thu'],
  },
}
