// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Gauge } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Feedback/Gauge',
  component: Gauge as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: { value: 0.5, label: 'cpu' },
}

export const Variant1: Story = {
  name: 'all',
  args: { value: 0.8, label: 'mem', color: '#0f0', size: 80 },
}

export const Variant2: Story = {
  name: 'high',
  args: { value: 1.5, label: 'hot' },
}
