// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { GroupedList } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Data display/GroupedList',
  component: GroupedList as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    groups: [
      { title: 'A', items: [{ label: 'one', sublabel: 's', meta: 'm', status: 'ok' }] },
      {
        title: 'B',
        items: [
          { label: 'two', status: 'warn' },
          { label: 'three', status: 'critical' },
        ],
      },
    ],
  },
}

export const Variant1: Story = {
  name: 'fixed',
  args: { groups: [{ title: 'A', items: [{ label: 'one' }] }], collapsible: false },
}
