// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { HeatMap } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: distribution/HeatMap',
  component: HeatMap,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof HeatMap>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    data: [
      [0, 0.5, 1],
      [1, 0.5, 0],
    ],
    xLabels: ['x', 'y', 'z'],
  },
}
