// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { HeatMap } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: distribution/HeatMap',
  component: HeatMap as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "data": [[0, 0.5, 1], [1, 0.5, 0]], "xLabels": ["x", "y", "z"] },
};
