// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Histogram } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: distribution/Histogram',
  component: Histogram,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Histogram>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    bins: [
      { x0: 0, x1: 10, count: 5 },
      { x0: 10, x1: 20, count: 8 },
    ],
    xUnit: 'ms',
  },
}
