// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { HorizonChart } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Charts: time-series/HorizonChart',
  component: HorizonChart as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    series: [
      { label: 'a', values: [1, 4, 2, 7, 5, 9] },
      { label: 'b', values: [1, 4, 2, 7, 5, 9], color: '#0f0' },
    ],
    xLabels: ['M', 'T', 'W', 'T', 'F', 'S'],
  },
}
