// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { IcicleChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: hierarchy & flow/IcicleChart',
  component: IcicleChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "root": { "label": "r", "children": [{ "label": "a", "value": 5 }, { "label": "b", "value": 10, "color": "#0f0" }] } },
};
