// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { IcicleChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: hierarchy & flow/IcicleChart',
  component: IcicleChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof IcicleChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    root: {
      label: 'r',
      children: [
        { label: 'a', value: 5 },
        { label: 'b', value: 10, color: '#0f0' },
      ],
    },
  },
}
