// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { IconButton } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/IconButton',
  component: IconButton,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof IconButton>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { title: 'x' },
}

export const Variant1: Story = {
  name: 'aria',
  args: {},
}
