// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { IconButton } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/IconButton',
  component: IconButton as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "title": "x" },
};

export const Variant1: Story = {
  name: "aria",
  args: {  },
};
