// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { InlineEdit } from '@w5-ui/svelte'

const meta = {
  title: 'Feedback/InlineEdit',
  component: InlineEdit,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof InlineEdit>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { value: 'hi', onConfirm: () => {}, label: 'Name' },
}

export const Variant1: Story = {
  name: 'placeholder',
  args: { value: '', onConfirm: () => {}, label: 'Name', placeholder: '...' },
}
