// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { InputGroup } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/InputGroup',
  component: InputGroup as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: {  },
};

export const Variant1: Story = {
  name: "pre suf",
  args: { "prefix": "$", "suffix": "USD" },
};
