// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { InputGroup } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/InputGroup',
  component: InputGroup,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof InputGroup>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {},
}

export const Variant1: Story = {
  name: 'pre suf',
  args: { prefix: '$', suffix: 'USD' },
}
