// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { IPInput } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/IPInput',
  component: IPInput,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof IPInput>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { label: 'IP' },
}

export const Variant1: Story = {
  name: 'controlled',
  args: { label: 'IP', value: '1.2.3.4', onChange: () => {} },
}

export const Variant2: Story = {
  name: 'disabled',
  args: { label: 'IP', disabled: true },
}
