// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { JsonViewer } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/JsonViewer',
  component: JsonViewer,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof JsonViewer>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'object',
  args: { data: { a: 1, b: [1, 2], c: { d: true, e: null, f: 'x' } } },
}

export const Variant1: Story = {
  name: 'collapsed',
  args: { data: { a: { b: { c: { d: 1 } } } }, defaultExpanded: false, maxDepth: 1 },
}

export const Variant2: Story = {
  name: 'array',
  args: { data: [1, 2, 3] },
}

export const Variant3: Story = {
  name: 'primitive',
  args: { data: 'hi' },
}
