// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { KanbanBoard } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/KanbanBoard',
  component: KanbanBoard,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof KanbanBoard>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    columns: [
      {
        id: 'todo',
        title: 'To do',
        color: '#0f0',
        cards: [{ id: '1', title: 'A', subtitle: 's', meta: 'm' }],
      },
      { id: 'done', title: 'Done', cards: [] },
    ],
  },
}

export const Variant1: Story = {
  name: 'no cb',
  args: { columns: [{ id: 'a', title: 'A', cards: [{ id: '1', title: 't' }] }] },
}
