// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { KanbanBoard } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Data display/KanbanBoard',
  component: KanbanBoard as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "columns": [{ "id": "todo", "title": "To do", "color": "#0f0", "cards": [{ "id": "1", "title": "A", "subtitle": "s", "meta": "m" }] }, { "id": "done", "title": "Done", "cards": [] }] },
};

export const Variant1: Story = {
  name: "no cb",
  args: { "columns": [{ "id": "a", "title": "A", "cards": [{ "id": "1", "title": "t" }] }] },
};
