// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Kbd } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/Kbd',
  component: Kbd,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Kbd>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'string',
  args: { keys: 'K' },
}

export const Variant1: Story = {
  name: 'array',
  args: { keys: ['Ctrl', 'K'] },
}
