// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { KVTable } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Data display/KVTable',
  component: KVTable as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "rows": [{ "label": "a", "value": "b" }] },
};

export const Variant1: Story = {
  name: "caption",
  args: { "rows": [{ "label": "a", "value": "b" }], "caption": "cap" },
};
