// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { KVTable } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/KVTable',
  component: KVTable,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof KVTable>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { rows: [{ label: 'a', value: 'b' }] },
}

export const Variant1: Story = {
  name: 'caption',
  args: { rows: [{ label: 'a', value: 'b' }], caption: 'cap' },
}
