// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { LogViewer } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Data display/LogViewer',
  component: LogViewer as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    entries: [
      { time: '00:00', level: 'info', message: 'hi' },
      { time: '00:01', level: 'warn', message: 'w' },
      { time: '00:02', level: 'error', message: 'e', source: 'src' },
      { time: '00:03', level: 'debug', message: 'd' },
    ],
  },
}

export const Variant1: Story = {
  name: 'no follow',
  args: { entries: [], defaultFollow: false },
}
