// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { LollipopChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: comparison/LollipopChart',
  component: LollipopChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof LollipopChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    items: [
      { label: 'A', value: 5 },
      { label: 'B', value: 10, color: '#0f0' },
    ],
    unit: 'ms',
  },
}
