// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { MACInput } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Inputs/MACInput',
  component: MACInput as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: { label: 'MAC' },
}

export const Variant1: Story = {
  name: 'controlled',
  args: { label: 'MAC', value: 'ff:ff:ff:ff:ff:ff', onChange: () => {} },
}

export const Variant2: Story = {
  name: 'disabled',
  args: { label: 'MAC', disabled: true },
}
