// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { MarimekkoChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: comparison/MarimekkoChart',
  component: MarimekkoChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof MarimekkoChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    columns: [
      {
        label: 'A',
        segments: [
          { label: 'a', value: 1 },
          { label: 'b', value: 2, color: '#0f0' },
        ],
      },
      { label: 'B', segments: [{ label: 'a', value: 2 }] },
    ],
  },
}

export const Variant1: Story = {
  name: 'empty',
  args: {
    columns: [
      { label: 'A', segments: [] },
      { label: 'B', segments: [{ label: 'x', value: 5 }] },
    ],
  },
}
