// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { MatrixChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: distribution/MatrixChart',
  component: MatrixChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof MatrixChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { rows: ['r1'], cols: ['c1', 'c2'], values: [[0.1, 0.5]], unit: 'x' },
}
