// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Menubar } from '@w5-ui/svelte'

const meta = {
  title: 'Selection & menus/Menubar',
  component: Menubar,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Menubar>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    menus: [
      {
        id: 'f',
        label: 'File',
        items: [
          { id: 'open', label: 'Open' },
          { id: 'sep', label: '', separator: true },
          { id: 'close', label: 'Close', disabled: true },
        ],
      },
      { id: 'e', label: 'Edit', items: [{ id: 'cut', label: 'Cut' }] },
    ],
    onAction: () => {},
  },
}
