// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { MirroredBarChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: comparison/MirroredBarChart',
  component: MirroredBarChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "items": [{ "label": "A", "left": 5, "right": 7 }], "unit": "GB" },
};
