// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { MirroredBarChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: comparison/MirroredBarChart',
  component: MirroredBarChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof MirroredBarChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { items: [{ label: 'A', left: 5, right: 7 }], unit: 'GB' },
}
