// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Modal } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Layout/Modal',
  component: Modal as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "open",
  args: { "open": true, "title": "t", "onClose": () => {} },
};

export const Variant1: Story = {
  name: "closed",
  args: { "open": false, "title": "t", "onClose": () => {} },
};
