// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Modal } from '@w5-ui/svelte'

const meta = {
  title: 'Layout/Modal',
  component: Modal,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Modal>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'open',
  args: { open: true, title: 't', onClose: () => {} },
}

export const Variant1: Story = {
  name: 'closed',
  args: { open: false, title: 't', onClose: () => {} },
}
