// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { NightingaleChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: comparison/NightingaleChart',
  component: NightingaleChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "segments": [{ "label": "A", "value": 5 }, { "label": "B", "value": 9, "color": "#0f0" }] },
};
