// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { NightingaleChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: comparison/NightingaleChart',
  component: NightingaleChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof NightingaleChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    segments: [
      { label: 'A', value: 5 },
      { label: 'B', value: 9, color: '#0f0' },
    ],
  },
}
