// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { NotificationPanel } from '@w5-ui/svelte'

const meta = {
  title: 'Feedback/NotificationPanel',
  component: NotificationPanel,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof NotificationPanel>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'open',
  args: {
    open: true,
    onClose: () => {},
    notifications: [
      { id: '1', title: 'hi', body: 'b', time: 'now', read: false, severity: 'info' },
      { id: '2', title: 'h2', body: 'b2', time: 'now', read: true, severity: 'warn' },
      { id: '3', title: 'h3', body: 'b3', time: 'now', read: false, severity: 'critical' },
    ],
    onMarkRead: () => {},
    onMarkAllRead: () => {},
  },
}

export const Variant1: Story = {
  name: 'closed',
  args: { open: false, onClose: () => {}, notifications: [] },
}
