// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { NumberInput } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/NumberInput',
  component: NumberInput,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof NumberInput>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { label: 'N' },
}

export const Variant1: Story = {
  name: 'controlled',
  args: { label: 'N', value: 5, onChange: () => {}, min: 0, max: 10, step: 2, suffix: 'x' },
}

export const Variant2: Story = {
  name: 'disabled',
  args: { label: 'N', disabled: true },
}
