// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { OTPInput } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/OTPInput',
  component: OTPInput,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof OTPInput>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { label: 'OTP' },
}

export const Variant1: Story = {
  name: 'controlled',
  args: { label: 'OTP', value: '123', onChange: () => {}, length: 4 },
}

export const Variant2: Story = {
  name: 'disabled',
  args: { label: 'OTP', disabled: true },
}
