// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { PageHeader } from '@w5-ui/svelte'

const meta = {
  title: 'Layout/PageHeader',
  component: PageHeader,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof PageHeader>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { title: 'Dashboard' },
}

export const Variant1: Story = {
  name: 'non-sticky',
  args: { title: 'Devices', sticky: false },
}
