// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Pagination } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Navigation/Pagination',
  component: Pagination as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: { page: 1, pageSize: 10, total: 50, onChange: () => {} },
}

export const Variant1: Story = {
  name: 'last',
  args: { page: 5, pageSize: 10, total: 50, onChange: () => {} },
}

export const Variant2: Story = {
  name: 'empty',
  args: { page: 1, pageSize: 10, total: 0, onChange: () => {} },
}
