// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ParallelCoordinates } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Charts: distribution/ParallelCoordinates',
  component: ParallelCoordinates as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    axes: [{ label: 'a' }, { label: 'b', range: [0, 10] }],
    series: [
      { label: 's', values: [1, 5] },
      { label: 's2', values: [3, 7], color: '#0f0' },
    ],
  },
}
