// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { ParetoChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: comparison/ParetoChart',
  component: ParetoChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "items": [{ "label": "A", "value": 50 }, { "label": "B", "value": 30 }, { "label": "C", "value": 20, "color": "#0f0" }], "threshold": 0.7 },
};
