// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { PasswordInput } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Inputs/PasswordInput',
  component: PasswordInput as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: { label: 'P' },
}

export const Variant1: Story = {
  name: 'controlled',
  args: {
    label: 'P',
    value: 'x',
    onChange: () => {},
    placeholder: 'pw',
    autocomplete: 'new-password',
  },
}

export const Variant2: Story = {
  name: 'disabled',
  args: { label: 'P', disabled: true },
}
