// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { PieChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: hierarchy & flow/PieChart',
  component: PieChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof PieChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    slices: [
      { label: 'A', value: 1, color: '#006FFF' },
      { label: 'B', value: 3, color: '#0f0' },
    ],
  },
}
