// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { PieChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: hierarchy & flow/PieChart',
  component: PieChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "slices": [{ "label": "A", "value": 1, "color": "#006FFF" }, { "label": "B", "value": 3, "color": "#0f0" }] },
};
