// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Pill } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/Pill',
  component: Pill,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Pill>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'success',
  args: { variant: 'success' },
}

export const Variant1: Story = {
  name: 'warn',
  args: { variant: 'warn' },
}

export const Variant2: Story = {
  name: 'danger',
  args: { variant: 'danger' },
}

export const Variant3: Story = {
  name: 'info',
  args: { variant: 'info' },
}

export const Variant4: Story = {
  name: 'neutral',
  args: {},
}

export const Variant5: Story = {
  name: 'no dot',
  args: { showDot: false },
}
