// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { PolarHeatmap } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: distribution/PolarHeatmap',
  component: PolarHeatmap,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof PolarHeatmap>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    data: [
      { row: 0, col: 0, value: 1 },
      { row: 1, col: 1, value: 0.5 },
    ],
    rows: 2,
    cols: 2,
    colLabels: ['c1', 'c2'],
  },
}
