// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Popover } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Selection & menus/Popover',
  component: Popover as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "label": "open" },
};

export const Variant1: Story = {
  name: "primary",
  args: { "label": "open", "variant": "primary", "title": "t", "placement": "top" },
};
