// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Popover } from '@w5-ui/svelte'

const meta = {
  title: 'Selection & menus/Popover',
  component: Popover,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Popover>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { label: 'open' },
}

export const Variant1: Story = {
  name: 'primary',
  args: { label: 'open', variant: 'primary', title: 't', placement: 'top' },
}
