// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Popover } from '@w5-ui/svelte'

const meta = {
  title: 'Selection & menus/Popover',
  component: Popover,
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component:
          'A **click-opened**, interactive surface anchored to its trigger: menus, pickers, filters. Focus moves into the panel and returns to the trigger; closes on outside click and `Escape`. For a control’s name use a Tooltip; for read-only extra detail on hover use a HoverCard.',
      },
    },
  },
  tags: ['autodocs'],
} satisfies Meta<typeof Popover>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { label: 'open' },
}

export const Variant1: Story = {
  name: 'primary',
  args: { label: 'open', variant: 'primary', title: 't', placement: 'top' },
}
