// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ProgressBar } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Feedback/ProgressBar',
  component: ProgressBar as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: { value: 0.5 },
}

export const Variant1: Story = {
  name: 'with label',
  args: { value: 0.9, label: 'cpu', valueText: '90%', color: '#0f0' },
}
