// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { PunchCard } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: distribution/PunchCard',
  component: PunchCard,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof PunchCard>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    data: [
      [0, 1, 2, 5, 3],
      [2, 1, 0, 4, 2],
      [3, 5, 1, 0, 6],
    ],
    rowLabels: ['r1', 'r2', 'r3'],
    colLabels: ['c1', 'c2', 'c3', 'c4', 'c5'],
  },
}

export const Variant1: Story = {
  name: 'no labels',
  args: {
    data: [
      [1, 2],
      [3, 4],
    ],
  },
}
