// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { QuadrantChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: distribution/QuadrantChart',
  component: QuadrantChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "points": [{ "x": 1, "y": 4, "label": "a" }, { "x": 9, "y": 9, "label": "b" }, { "x": 1, "y": 1, "label": "c" }, { "x": 9, "y": 1, "label": "d" }], "xThreshold": 5, "yThreshold": 5 },
};

export const Variant1: Story = {
  name: "all options",
  args: { "points": [{ "x": 5, "y": 5, "label": "mid" }], "xThreshold": 5, "yThreshold": 5, "xRange": [0, 10], "yRange": [0, 10], "xLabel": "cost", "yLabel": "value" },
};
