// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { RadarChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: comparison/RadarChart',
  component: RadarChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof RadarChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    series: [{ label: 'a', color: '#006FFF', values: [0.2, 0.5, 0.8, 0.3] }],
    axes: ['a', 'b', 'c', 'd'],
  },
}
