// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { RadioGroup } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/RadioGroup',
  component: RadioGroup as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "legend": "L", "options": [{ "value": "a", "label": "A" }, { "value": "b", "label": "B", "description": "d", "disabled": true }] },
};

export const Variant1: Story = {
  name: "controlled",
  args: { "legend": "L", "name": "n", "options": [{ "value": "a", "label": "A" }, { "value": "b", "label": "B" }], "value": "b", "onChange": () => {}, "srOnlyLegend": true, "horizontal": true },
};

export const Variant2: Story = {
  name: "default value",
  args: { "legend": "L", "options": [{ "value": "a", "label": "A" }], "defaultValue": "a" },
};
