// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { RadialBarChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: comparison/RadialBarChart',
  component: RadialBarChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof RadialBarChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    items: [
      { label: 'A', value: 60, max: 100 },
      { label: 'B', value: 80, max: 100, color: '#0f0', unit: '%' },
    ],
  },
}

export const Variant1: Story = {
  name: 'over',
  args: { items: [{ label: 'A', value: 200, max: 100 }] },
}
