// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { RangeSlider } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/RangeSlider',
  component: RangeSlider as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "label": "R" },
};

export const Variant1: Story = {
  name: "controlled",
  args: { "label": "R", "low": 20, "high": 80, "onChange": () => {}, "suffix": "%" },
};

export const Variant2: Story = {
  name: "defaults",
  args: { "label": "R", "defaultLow": 10, "defaultHigh": 90, "step": 5, "disabled": true },
};
