// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { RankedList } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Data display/RankedList',
  component: RankedList as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    items: [
      { label: 'A', value: 50, sublabel: 's' },
      { label: 'B', value: 80, color: '#0f0' },
    ],
    unit: 'ms',
  },
}

export const Variant1: Story = {
  name: 'fixed',
  args: { items: [{ label: 'A', value: 50 }], max: 100 },
}
