// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ResizablePanel } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Layout/ResizablePanel',
  component: ResizablePanel as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'vertical',
  args: {},
}

export const Variant1: Story = {
  name: 'horizontal',
  args: { orientation: 'horizontal', defaultSize: 30, min: 10, max: 90 },
}
