// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { RidgelinePlot } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: distribution/RidgelinePlot',
  component: RidgelinePlot as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "series": [{ "label": "a", "values": [1, 4, 2, 7, 5, 9] }, { "label": "b", "values": [1, 4, 2, 7, 5, 9], "color": "#0f0" }] },
};

export const Variant1: Story = {
  name: "fixed",
  args: { "series": [{ "label": "a", "values": [1, 4, 2, 7, 5, 9] }], "xRange": [0, 10] },
};
