// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { RowToggle } from '@w5-ui/svelte'

const meta = {
  title: 'Specialised/RowToggle',
  component: RowToggle,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof RowToggle>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { title: 't', description: 'd', on: false },
}

export const Variant1: Story = {
  name: 'on',
  args: { title: 't', description: 'd', on: true, onToggle: () => {} },
}
