// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { SankeyDiagram } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Charts: hierarchy & flow/SankeyDiagram',
  component: SankeyDiagram as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    nodes: [
      { id: 'a', label: 'A' },
      { id: 'b', label: 'B', color: '#0f0' },
      { id: 'c', label: 'C' },
    ],
    links: [
      { source: 'a', target: 'b', value: 5 },
      { source: 'b', target: 'c', value: 3 },
    ],
  },
}
