// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { SearchBox } from '@w5-ui/svelte'

const meta = {
  title: 'Specialised/SearchBox',
  component: SearchBox,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof SearchBox>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {},
}

export const Variant1: Story = {
  name: 'placeholder',
  args: { placeholder: 'Search devices' },
}
