// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { SegmentedControl } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/SegmentedControl',
  component: SegmentedControl as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "label": "L", "options": [{ "value": "a", "label": "A" }, { "value": "b", "label": "B", "disabled": true }] },
};

export const Variant1: Story = {
  name: "controlled",
  args: { "label": "L", "options": [{ "value": "a", "label": "A" }, { "value": "b", "label": "B" }], "value": "b", "onChange": () => {} },
};

export const Variant2: Story = {
  name: "default value",
  args: { "label": "L", "options": [{ "value": "a", "label": "A" }], "defaultValue": "a" },
};
