// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { SegmentedControl } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/SegmentedControl',
  component: SegmentedControl,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof SegmentedControl>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    label: 'L',
    options: [
      { value: 'a', label: 'A' },
      { value: 'b', label: 'B', disabled: true },
    ],
  },
}

export const Variant1: Story = {
  name: 'controlled',
  args: {
    label: 'L',
    options: [
      { value: 'a', label: 'A' },
      { value: 'b', label: 'B' },
    ],
    value: 'b',
    onChange: () => {},
  },
}

export const Variant2: Story = {
  name: 'default value',
  args: { label: 'L', options: [{ value: 'a', label: 'A' }], defaultValue: 'a' },
}
