// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { SelectionToolbar } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/SelectionToolbar',
  component: SelectionToolbar,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof SelectionToolbar>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    count: 3,
    actions: [
      { id: 'd', label: 'Delete', danger: true },
      { id: 'e', label: 'Edit' },
    ],
    onClear: () => {},
  },
}
