// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Select } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/Select',
  component: Select as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "options": [{ "value": "a", "label": "A" }] },
};

export const Variant1: Story = {
  name: "controlled",
  args: { "options": [{ "value": "a", "label": "A" }, { "value": "b", "label": "B" }], "value": "b", "onChange": () => {}, "label": "L" },
};

export const Variant2: Story = {
  name: "disabled",
  args: { "options": [{ "value": "a", "label": "A" }], "disabled": true },
};
