// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Sidebar } from '@w5-ui/svelte'

const meta = {
  title: 'Specialised/Sidebar',
  component: Sidebar,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Sidebar>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    activeId: 'dash',
    sections: [
      {
        title: 'Manage',
        items: [
          { id: 'dash', label: 'Dashboard', count: 3, pill: 1 },
          { id: 'devs', label: 'Devices' },
        ],
      },
    ],
    onChange: () => {},
  },
}
