// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Sidebar } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Specialised/Sidebar',
  component: Sidebar as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "activeId": "dash", "sections": [{ "title": "Manage", "items": [{ "id": "dash", "label": "Dashboard", "count": 3, "pill": 1 }, { "id": "devs", "label": "Devices" }] }], "onChange": () => {} },
};
