// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Signal } from '@w5-ui/svelte'

const meta = {
  title: 'Feedback/Signal',
  component: Signal,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Signal>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { label: 'ok' },
}

export const Variant1: Story = {
  name: 'weak',
  args: { weak: true, label: 'weak' },
}
