// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Skeleton } from '@w5-ui/svelte'

const meta = {
  title: 'Feedback/Skeleton',
  component: Skeleton,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Skeleton>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'text',
  args: {},
}

export const Variant1: Story = {
  name: 'rect',
  args: { variant: 'rect', width: 100, height: 20 },
}

export const Variant2: Story = {
  name: 'circle',
  args: { variant: 'circle', width: '40px', height: '40px' },
}
