// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { SkipLink } from '@w5-ui/svelte'

const meta = {
  title: 'Navigation/SkipLink',
  component: SkipLink,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof SkipLink>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {},
}

export const Variant1: Story = {
  name: 'custom',
  args: { href: '#x' },
}
