// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Slider } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/Slider',
  component: Slider as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "label": "L" },
};

export const Variant1: Story = {
  name: "controlled",
  args: { "label": "L", "value": 50, "onChange": () => {}, "min": 0, "max": 100, "step": 5, "suffix": "%" },
};

export const Variant2: Story = {
  name: "disabled",
  args: { "label": "L", "disabled": true },
};
