// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { SlopeChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: comparison/SlopeChart',
  component: SlopeChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof SlopeChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    items: [
      { label: 'A', before: 5, after: 8 },
      { label: 'B', before: 9, after: 4 },
    ],
    unit: 'ms',
    positiveIsGood: true,
  },
}

export const Variant1: Story = {
  name: 'no flag',
  args: {
    items: [
      { label: 'A', before: 5, after: 5 },
      { label: 'B', before: 1, after: 9 },
    ],
  },
}
