// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { SortableList } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Data display/SortableList',
  component: SortableList as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "items": [{ "id": "1", "label": "A", "meta": "m" }, { "id": "2", "label": "B" }], "onChange": () => {} },
};

export const Variant1: Story = {
  name: "aria",
  args: { "items": [{ "id": "1", "label": "A" }], "onChange": () => {}, "ariaLabel": "x" },
};
