// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { SortHeader } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Specialised/SortHeader',
  component: SortHeader as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "asc active",
  args: { "sortKey": "a", "activeKey": "a", "dir": "asc", "onSort": () => {} },
};

export const Variant1: Story = {
  name: "desc active",
  args: { "sortKey": "a", "activeKey": "a", "dir": "desc", "onSort": () => {} },
};

export const Variant2: Story = {
  name: "inactive",
  args: { "sortKey": "a", "activeKey": "b", "dir": "asc", "onSort": () => {} },
};
