// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { SortableList } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/SortableList',
  component: SortableList,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof SortableList>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    items: [
      { id: '1', label: 'A', meta: 'm' },
      { id: '2', label: 'B' },
    ],
    onChange: () => {},
  },
}

export const Variant1: Story = {
  name: 'aria',
  args: { items: [{ id: '1', label: 'A' }], onChange: () => {}, ariaLabel: 'x' },
}
