// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Sparkline } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Charts: time-series/Sparkline',
  component: Sparkline as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {},
}

export const Variant1: Story = {
  name: 'active',
  args: { bars: 10, active: true, seed: 42 },
}
