// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { SparklineMatrix } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: time-series/SparklineMatrix',
  component: SparklineMatrix,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof SparklineMatrix>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    rows: [
      { label: 'a', values: [1, 4, 2, 7, 5, 9] },
      {
        label: 'b',
        values: [10, 30, 20, 40],
        color: '#0f0',
        meta: 'm',
        delta: '+1',
        deltaDir: 'up',
      },
      { label: 'c', values: [1, 1], delta: '-1', deltaDir: 'down' },
    ],
  },
}
