// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Spinner } from '@w5-ui/svelte'

const meta = {
  title: 'Feedback/Spinner',
  component: Spinner,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Spinner>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {},
}

export const Variant1: Story = {
  name: 'sm',
  args: { size: 'sm', label: 'loading' },
}

export const Variant2: Story = {
  name: 'lg',
  args: { size: 'lg' },
}
