// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { SplitButton } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Inputs/SplitButton',
  component: SplitButton as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    label: 'Save',
    items: [
      { id: 'a', label: 'Save as' },
      { id: 'b', label: 'Save copy', disabled: true },
    ],
    onPrimaryClick: () => {},
    onAction: () => {},
  },
}

export const Variant1: Story = {
  name: 'primary',
  args: { label: 'x', variant: 'primary', disabled: true, items: [{ id: 'a', label: 'A' }] },
}

export const Variant2: Story = {
  name: 'danger',
  args: { label: 'x', variant: 'danger', items: [{ id: 'a', label: 'A' }] },
}
