// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Spoiler } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/Spoiler',
  component: Spoiler,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Spoiler>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {},
}

export const Variant1: Story = {
  name: 'custom',
  args: { maxHeight: 20, showLabel: 'more', hideLabel: 'less' },
}
