// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { StackedBarChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: comparison/StackedBarChart',
  component: StackedBarChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "series": [{ "label": "A", "color": "#006FFF", "values": [10, 30, 20, 40] }, { "label": "B", "color": "#00C8C8", "values": [5, 18, 22, 17] }], "labels": ["Mon", "Tue", "Wed", "Thu"] },
};

export const Variant1: Story = {
  name: "normalised",
  args: { "series": [{ "label": "A", "color": "#006FFF", "values": [10, 30, 20, 40] }, { "label": "B", "color": "#00C8C8", "values": [5, 18, 22, 17] }], "labels": ["Mon", "Tue", "Wed", "Thu"], "normalized": true },
};
