// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { StarRating } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Inputs/StarRating',
  component: StarRating as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: { label: 'rate' },
}

export const Variant1: Story = {
  name: 'controlled',
  args: { label: 'rate', value: 3, onChange: () => {}, max: 6, size: 'sm' },
}

export const Variant2: Story = {
  name: 'readonly',
  args: { label: 'rate', value: 4, readOnly: true },
}

export const Variant3: Story = {
  name: 'default value',
  args: { label: 'rate', defaultValue: 2 },
}
