// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { StatusIndicator } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Feedback/StatusIndicator',
  component: StatusIndicator as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: { color: '#0f0', text: 'ok' },
}

export const Variant1: Story = {
  name: 'with textColor',
  args: { color: '#0f0', text: 'ok', textColor: '#fff' },
}
