// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Stat } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Feedback/Stat',
  component: Stat as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: { label: 'L', value: 42 },
}

export const Variant1: Story = {
  name: 'all options',
  args: {
    label: 'L',
    value: '42',
    unit: 'ms',
    sub: 'sub',
    delta: '+1',
    deltaDir: 'up',
    span: 2,
    color: '#0f0',
  },
}

export const Variant2: Story = {
  name: 'down',
  args: { label: 'L', value: '42', delta: '-1', deltaDir: 'down' },
}
