// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Stepper } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Navigation/Stepper',
  component: Stepper as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "steps": [{ "id": "a", "label": "A" }, { "id": "b", "label": "B" }, { "id": "c", "label": "C" }], "active": "b" },
};

export const Variant1: Story = {
  name: "with class",
  args: { "steps": [{ "id": "a", "label": "A" }], "active": "a" },
};
