// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Stepper } from '@w5-ui/svelte'

const meta = {
  title: 'Navigation/Stepper',
  component: Stepper,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Stepper>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    steps: [
      { id: 'a', label: 'A' },
      { id: 'b', label: 'B' },
      { id: 'c', label: 'C' },
    ],
    active: 'b',
  },
}

export const Variant1: Story = {
  name: 'with class',
  args: { steps: [{ id: 'a', label: 'A' }], active: 'a' },
}
