// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { StreamGraph } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Charts: time-series/StreamGraph',
  component: StreamGraph as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    labels: ['Mon', 'Tue', 'Wed', 'Thu'],
    series: [
      { label: 'a', values: [10, 30, 20, 40] },
      { label: 'b', values: [5, 18, 22, 17], color: '#0f0' },
    ],
  },
}
