// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { StripeChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: distribution/StripeChart',
  component: StripeChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof StripeChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    data: [
      { label: 'A', value: 1 },
      { label: 'B', value: 5 },
    ],
  },
}
