// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { SunburstChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: hierarchy & flow/SunburstChart',
  component: SunburstChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "root": { "label": "r", "children": [{ "label": "a", "value": 1 }, { "label": "b", "value": 2, "color": "#0f0", "children": [{ "label": "b1", "value": 3 }] }] } },
};
