// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { SunburstChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: hierarchy & flow/SunburstChart',
  component: SunburstChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof SunburstChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    root: {
      label: 'r',
      children: [
        { label: 'a', value: 1 },
        { label: 'b', value: 2, color: '#0f0', children: [{ label: 'b1', value: 3 }] },
      ],
    },
  },
}
