// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { SwitchPortGrid } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/SwitchPortGrid',
  component: SwitchPortGrid,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof SwitchPortGrid>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    ports: [
      { index: 1, status: 'up', speed: '1G' },
      { index: 2, status: 'down', speed: '1G' },
      { index: 3, status: 'disabled', speed: '1G' },
      { index: 4, status: 'poe', speed: '1G' },
      { index: 5, status: 'up', speed: '1G' },
      { index: 6, status: 'down', speed: '1G' },
      { index: 7, status: 'disabled', speed: '1G' },
      { index: 8, status: 'poe', speed: '1G' },
    ],
    columns: 4,
    onPortClick: () => {},
  },
}
