// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { TabPanel } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Specialised/TabPanel',
  component: TabPanel as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "active",
  args: { "id": "a", "active": "a" },
};

export const Variant1: Story = {
  name: "inactive",
  args: { "id": "a", "active": "b" },
};
