// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { TabPanel } from '@w5-ui/svelte'

const meta = {
  title: 'Specialised/TabPanel',
  component: TabPanel,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof TabPanel>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'active',
  args: { id: 'a', active: 'a' },
}

export const Variant1: Story = {
  name: 'inactive',
  args: { id: 'a', active: 'b' },
}
