// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Tabs } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Navigation/Tabs',
  component: Tabs as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    items: [
      { id: 'a', label: 'A' },
      { id: 'b', label: 'B' },
    ],
    active: 'a',
    onChange: () => {},
  },
}

export const Variant1: Story = {
  name: 'with aria',
  args: { items: [{ id: 'a', label: 'A' }], active: 'a', ariaLabel: 't' },
}
