// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Tag } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Data display/Tag',
  component: Tag as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "label": "x" },
};

export const Variant1: Story = {
  name: "removable",
  args: { "label": "x", "onRemove": () => {} },
};
