// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Tag } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/Tag',
  component: Tag,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Tag>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { label: 'x' },
}

export const Variant1: Story = {
  name: 'removable',
  args: { label: 'x', onRemove: () => {} },
}
