// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { TagInput } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/TagInput',
  component: TagInput as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "label": "L" },
};

export const Variant1: Story = {
  name: "controlled",
  args: { "label": "L", "value": ["a"], "onChange": () => {}, "placeholder": "p" },
};

export const Variant2: Story = {
  name: "disabled",
  args: { "label": "L", "disabled": true, "defaultValue": ["a", "b"] },
};
