// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { TagInput } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/TagInput',
  component: TagInput,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof TagInput>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { label: 'L' },
}

export const Variant1: Story = {
  name: 'controlled',
  args: { label: 'L', value: ['a'], onChange: () => {}, placeholder: 'p' },
}

export const Variant2: Story = {
  name: 'disabled',
  args: { label: 'L', disabled: true, defaultValue: ['a', 'b'] },
}
