// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Textarea } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/Textarea',
  component: Textarea,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Textarea>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {},
}

export const Variant1: Story = {
  name: 'with rows',
  args: { rows: 6 },
}
