// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { ThresholdAreaChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: time-series/ThresholdAreaChart',
  component: ThresholdAreaChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof ThresholdAreaChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    values: [1, 4, 2, 7, 5, 9],
    labels: ['M', 'T', 'W', 'T', 'F', 'S'],
    threshold: 5,
    thresholdLabel: 'warn',
  },
}
