// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Timeline } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Data display/Timeline',
  component: Timeline as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "events": [{ "id": "1", "title": "a", "time": "now" }, { "id": "2", "title": "b", "time": "later", "description": "d", "icon": "x" }] },
};
