// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Timeline } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/Timeline',
  component: Timeline,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Timeline>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    events: [
      { id: '1', title: 'a', time: 'now' },
      { id: '2', title: 'b', time: 'later', description: 'd', icon: 'x' },
    ],
  },
}
