// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Toaster } from '@w5-ui/svelte'

const meta = {
  title: 'Feedback/Toast',
  component: Toaster,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Toaster>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {},
}
