// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { ToggleGroup } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Inputs/ToggleGroup',
  component: ToggleGroup as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "options": [{ "value": "a", "label": "A" }, { "value": "b", "label": "B", "disabled": true }], "value": ["a"], "onChange": () => {}, "ariaLabel": "t" },
};

export const Variant1: Story = {
  name: "sm",
  args: { "options": [{ "value": "a", "label": "A" }], "value": [], "onChange": () => {}, "ariaLabel": "t", "size": "sm" },
};
