// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Toggle } from '@w5-ui/svelte'

const meta = {
  title: 'Inputs/Toggle',
  component: Toggle,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Toggle>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'off',
  args: { on: false, ariaLabel: 't' },
}

export const Variant1: Story = {
  name: 'on',
  args: { on: true, onToggle: () => {}, ariaDescribedBy: 'd' },
}
