// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Tooltip } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Selection & menus/Tooltip',
  component: Tooltip as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "label": "t" },
};
