// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Tooltip } from '@w5-ui/svelte'

const meta = {
  title: 'Selection & menus/Tooltip',
  component: Tooltip,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Tooltip>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { label: 't' },
}
