// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { Topbar } from '@w5-ui/svelte'

const meta = {
  title: 'Specialised/Topbar',
  component: Topbar,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof Topbar>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: { siteName: 'HQ', activeApp: 'network' },
}

export const Variant1: Story = {
  name: 'with apps',
  args: {
    siteName: 'HQ',
    activeApp: 'network',
    onAppChange: () => {},
    initials: 'WB',
    notificationCount: 5,
  },
}
