// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { Topbar } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Specialised/Topbar',
  component: Topbar as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "siteName": "HQ", "activeApp": "network" },
};

export const Variant1: Story = {
  name: "with apps",
  args: { "siteName": "HQ", "activeApp": "network", "onAppChange": () => {}, "initials": "WB", "notificationCount": 5 },
};
