// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { TransferList } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/TransferList',
  component: TransferList,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof TransferList>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {},
}

export const Variant1: Story = {
  name: 'with items',
  args: {
    sourceLabel: 'src',
    targetLabel: 'tgt',
    defaultSource: [{ id: '1', label: 'A', description: 'd' }],
    defaultTarget: [{ id: '2', label: 'B' }],
    onChange: () => {},
  },
}

export const Variant2: Story = {
  name: 'controlled',
  args: { source: [{ id: '1', label: 'A' }], target: [{ id: '2', label: 'B' }] },
}
