// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { TreeMap } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Charts: hierarchy & flow/TreeMap',
  component: TreeMap as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    nodes: [
      { label: 'A', value: 5 },
      { label: 'B', value: 10, color: '#0f0' },
    ],
  },
}
