// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { TreeBrowser } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/TreeBrowser',
  component: TreeBrowser,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof TreeBrowser>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    rootId: 'root',
    collections: {
      root: { id: 'root', name: '', collections: ['folder'], items: ['a'] },
      folder: { id: 'folder', name: 'folder', descriptor: '1 item', items: ['b'] },
    },
    items: { a: { id: 'a', name: 'A', descriptor: 'spec' }, b: { id: 'b', name: 'B' } },
    defaultExpanded: ['folder'],
    selected: 'a',
    onselect: () => {},
    label: 'Files',
  },
}

export const Variant1: Story = {
  name: 'deep nesting',
  args: {
    rootId: 'root',
    collections: {
      root: { id: 'root', name: '', collections: ['docs'] },
      docs: { id: 'docs', name: 'docs', collections: ['spec'], items: ['readme'] },
      spec: { id: 'spec', name: 'spec', descriptor: '2 files', items: ['rules', 'interface'] },
    },
    items: {
      readme: { id: 'readme', name: 'README' },
      rules: { id: 'rules', name: 'RULES' },
      interface: { id: 'interface', name: 'INTERFACE' },
    },
    defaultExpanded: ['docs', 'spec'],
    label: 'Docs',
  },
}

export const Variant2: Story = {
  name: 'controlled expansion',
  args: {
    rootId: 'root',
    collections: {
      root: { id: 'root', name: '', collections: ['folder'] },
      folder: { id: 'folder', name: 'folder', items: ['a'] },
    },
    items: { a: { id: 'a', name: 'A' } },
    expanded: ['folder'],
    ontoggle: () => {},
    label: 'Files',
  },
}

export const Variant3: Story = {
  name: 'empty',
  args: { rootId: 'root', collections: { root: { id: 'root', name: '' } } },
}
