// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { TreeView } from '@w5-ui/svelte'

const meta: Meta = {
  title: 'Data display/TreeView',
  component: TreeView as any,
  parameters: { layout: 'padded' },
}
export default meta

type Story = StoryObj

export const Variant0: Story = {
  name: 'default',
  args: {
    nodes: [
      { id: 'a', label: 'A', children: [{ id: 'b', label: 'B', icon: 'x', meta: 'm' }] },
      { id: 'c', label: 'C' },
    ],
    defaultExpanded: ['a'],
    selected: 'b',
    onSelect: () => {},
    label: 'L',
  },
}

export const Variant1: Story = {
  name: 'flat',
  args: { nodes: [{ id: 'a', label: 'A' }] },
}
