// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { TreeMap } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: hierarchy & flow/TreeMap',
  component: TreeMap,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof TreeMap>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    nodes: [
      { label: 'A', value: 5 },
      { label: 'B', value: 10, color: '#0f0' },
    ],
  },
}
