// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { UptimeTimeline } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: time-series/UptimeTimeline',
  component: UptimeTimeline,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof UptimeTimeline>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    series: [
      {
        label: 'A',
        segments: [
          { from: 0, to: 5, status: 'up' },
          { from: 5, to: 8, status: 'degraded' },
          { from: 8, to: 10, status: 'down' },
        ],
      },
    ],
    xLabels: ['0', '5', '10'],
  },
}
