// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { VennDiagram } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: hierarchy & flow/VennDiagram',
  component: VennDiagram as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "two sets",
  args: { "sets": [{ "label": "A", "size": 10 }, { "label": "B", "size": 8 }], "intersections": [{ "sets": ["A", "B"], "size": 3 }] },
};

export const Variant1: Story = {
  name: "three sets",
  args: { "sets": [{ "label": "A", "size": 10, "color": "#0f0" }, { "label": "B", "size": 8 }, { "label": "C", "size": 6 }] },
};
