// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { ViolinPlot } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: distribution/ViolinPlot',
  component: ViolinPlot as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "series": [{ "label": "A", "values": [1, 2, 2, 3, 4, 5, 5, 6] }, { "label": "B", "values": [2, 3, 3, 4, 5], "color": "#0f0" }] },
};

export const Variant1: Story = {
  name: "yRange",
  args: { "series": [{ "label": "A", "values": [1, 2, 3] }], "yRange": [0, 10] },
};
