// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { VirtualList } from '@w5-ui/svelte'

const meta = {
  title: 'Data display/VirtualList',
  component: VirtualList,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof VirtualList>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    items: [
      0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
      26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
    ],
    itemHeight: 20,
    height: 100,
    label: 'L',
  },
}

export const Variant1: Story = {
  name: 'overscan',
  args: { items: [1, 2], itemHeight: 20, height: 50, overscan: 5 },
}
