// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte';
import { WaffleChart } from '@dash-ui/svelte';

const meta: Meta = {
  title: 'Charts: comparison/WaffleChart',
  component: WaffleChart as any,
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

export const Variant0: Story = {
  name: "default",
  args: { "segments": [{ "label": "A", "value": 30 }, { "label": "B", "value": 20, "color": "#0f0" }] },
};

export const Variant1: Story = {
  name: "with total",
  args: { "segments": [{ "label": "A", "value": 30 }], "total": 100, "cols": 5, "rows": 5, "gap": 1 },
};
