// AUTO-GENERATED by scripts/generate-stories-svelte.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/svelte'
import { WaterfallChart } from '@w5-ui/svelte'

const meta = {
  title: 'Charts: hierarchy & flow/WaterfallChart',
  component: WaterfallChart,
  parameters: { layout: 'padded' },
} satisfies Meta<typeof WaterfallChart>
export default meta

type Story = StoryObj<typeof meta>

export const Variant0: Story = {
  name: 'default',
  args: {
    bars: [
      { label: 'a', value: 10, kind: 'start' },
      { label: 'b', value: 5, kind: 'pos' },
      { label: 'c', value: -3, kind: 'neg' },
      { label: 'd', value: 12, kind: 'end' },
    ],
  },
}
