#!/usr/bin/env tsx
// Reads the React fixtures registry source and emits one Storybook CSF file
// per component into apps/storybook-react/src/components.
//
// We parse the fixtures source textually (no dynamic import) so this script
// stays vanilla TS / no JSX. For each component we count the variants by
// counting "{ name:" within its array literal block.

import { mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { categoryFor } from '../packages/storybook-meta/src/categories.js';

const fixturesPath = path.resolve('packages/react/test-fixtures/fixtures.tsx');
const src = await readFile(fixturesPath, 'utf8');

// Find each component block: `  Foo: [` ... balanced `],`
function variantsFor(name: string): number {
  const re = new RegExp(`^\\s{2}${name}:\\s*\\[`, 'm');
  const m = re.exec(src);
  if (!m) return 0;
  const start = m.index + m[0].length;
  let depth = 1;
  let i = start;
  while (i < src.length && depth > 0) {
    const ch = src[i]!;
    if (ch === '[') depth++;
    else if (ch === ']') depth--;
    i++;
  }
  const body = src.slice(start, i - 1);
  return (body.match(/\{\s*name:/g) ?? []).length;
}

// Collect component names from `  ComponentName: [`
const names = Array.from(src.matchAll(/^\s{2}([A-Z]\w*):\s*\[/gm), (m) => m[1]!);

// Plus the icons appended programmatically in fixtures.tsx
const ICON_NAMES = [
  'SearchIcon', 'PlusIcon', 'DownloadIcon', 'CaretIcon', 'CloseIcon', 'BellIcon',
  'HelpIcon', 'UpdatesIcon', 'DashboardIcon', 'DevicesIcon', 'ClientsIcon',
  'TopologyIcon', 'AlarmIcon', 'LogsIcon', 'WifiIcon', 'PortsIcon', 'VpnIcon',
  'SecurityIcon', 'SettingsIcon', 'AirviewIcon', 'InfraIcon', 'IntegrationsIcon',
];
const ICON_VARIANTS = 2; // matches fixtures.tsx
const ICON_SET = new Set(ICON_NAMES);

const all = Array.from(new Set([...names, ...ICON_NAMES])).sort();

const outDir = path.resolve('apps/storybook-react/src/components');
await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

let written = 0;
for (const name of all) {
  const isIcon = ICON_SET.has(name);
  const titleCategory = isIcon ? 'Foundations/Icons' : categoryFor(name);
  const count = isIcon ? ICON_VARIANTS : variantsFor(name);
  if (count === 0) {
    console.warn(`No fixtures for ${name}; skipping`);
    continue;
  }

  const variantExports = Array.from({ length: count }, (_, i) => {
    const safeName = `Variant${i}`;
    return `export const ${safeName}: Story = {
  name: variants[${i}]!.name,
  render: () => variants[${i}]!.node as any,
};`;
  }).join('\n\n');

  const file = `// AUTO-GENERATED by scripts/generate-stories-react.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/react';
import { FIXTURES } from '../../../../packages/react/test-fixtures/fixtures.js';

const variants = FIXTURES.${name}!;

const meta: Meta = {
  title: '${titleCategory}/${name}',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

${variantExports}
`;
  await writeFile(path.join(outDir, `${name}.stories.tsx`), file);
  written++;
}

console.log(`Wrote ${written} story files to ${outDir}`);
