#!/usr/bin/env tsx
// Generates one .stories.ts file per registered custom element. Each story
// renders the element via lit-html, wiring properties from the same prop
// bundles used by the Svelte tests.

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { categoryFor } from '../packages/storybook-meta/src/categories.js';
import { BUNDLES } from '../packages/svelte/test-fixtures/props.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..');
const OUT_DIR = path.join(REPO_ROOT, 'apps/storybook-wc/src/components');

interface ManifestEntry {
  name: string;
  tag: string;
}

const manifest = JSON.parse(
  await readFile(path.join(REPO_ROOT, 'packages/wc/src/manifest.json'), 'utf8'),
) as ManifestEntry[];

const ICON_NAMES = new Set([
  'SearchIcon', 'PlusIcon', 'DownloadIcon', 'CaretIcon', 'CloseIcon', 'BellIcon',
  'HelpIcon', 'UpdatesIcon', 'DashboardIcon', 'DevicesIcon', 'ClientsIcon',
  'TopologyIcon', 'AlarmIcon', 'LogsIcon', 'WifiIcon', 'PortsIcon', 'VpnIcon',
  'SecurityIcon', 'SettingsIcon', 'WirelessIcon', 'InfraIcon', 'IntegrationsIcon',
]);

await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });

function serialise(value: unknown): string {
  if (value === null) return 'null';
  if (value === undefined) return 'undefined';
  if (value instanceof Date) return `new Date(${JSON.stringify(value.toISOString())})`;
  if (value instanceof Set) return `new Set(${JSON.stringify(Array.from(value))})`;
  if (typeof value === 'function') return '() => {}';
  if (Array.isArray(value)) return `[${value.map(serialise).join(', ')}]`;
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>).map(
      ([k, v]) => `${JSON.stringify(k)}: ${serialise(v)}`,
    );
    return `{ ${entries.join(', ')} }`;
  }
  return JSON.stringify(value);
}

let written = 0;
let skipped = 0;
for (const { name, tag } of manifest) {
  const variants = BUNDLES[name];
  if (!variants) {
    skipped++;
    continue;
  }

  const isIcon = ICON_NAMES.has(name);
  const titleCategory = isIcon ? 'Foundations/Icons' : categoryFor(name);

  const variantLines = variants
    .map((v, i) => {
      const safeName = `Variant${i}`;
      const propsExpr = serialise(v.props ?? {});
      return `export const ${safeName}: Story = {
  name: ${JSON.stringify(v.name)},
  render: () => {
    const props: Record<string, unknown> = ${propsExpr};
    const el = document.createElement('${tag}');
    for (const [k, v] of Object.entries(props)) (el as any)[k] = v;
    ${v.slot ? `el.textContent = ${JSON.stringify(v.slot)};` : ''}
    return el;
  },
};`;
    })
    .join('\n\n');

  const file = `// AUTO-GENERATED by scripts/generate-stories-wc.ts. Do not edit by hand.
import type { Meta, StoryObj } from '@storybook/web-components';

const meta: Meta = {
  title: '${titleCategory}/${name}',
  parameters: { layout: 'padded' },
};
export default meta;

type Story = StoryObj;

${variantLines}
`;
  await writeFile(path.join(OUT_DIR, `${name}.stories.ts`), file);
  written++;
}

console.log(`Wrote ${written} WC stories to ${OUT_DIR} (skipped ${skipped})`);
